'use client';
import {useEffect,useMemo,useState} from 'react';
import {supabase,isSupabaseConfigured} from '../../../lib/supabase';
type Row={id:string;slug:string;name:string;specialty:string|null;template_key:string;status:string;city:string|null;updated_at:string};
const SITE_BASE='https://sites.37lab.com.br';
export default function Clientes(){
 const[user,setUser]=useState<any>();const[rows,setRows]=useState<Row[]>([]);const[loading,setLoading]=useState(true);const[msg,setMsg]=useState('');const[q,setQ]=useState('');const[filter,setFilter]=useState('all');
 async function load(){const client=supabase;if(!client)return;setLoading(true);const{data,error}=await client.from('professionals').select('id,slug,name,specialty,template_key,status,city,updated_at').order('updated_at',{ascending:false});if(error)setMsg(error.message);else setRows(data||[]);setLoading(false)}
 useEffect(()=>{const client=supabase;if(!client)return;client.auth.getUser().then(({data})=>{setUser(data.user);if(data.user)load()})},[]);
 async function setStatus(r:Row,status:string){const client=supabase;if(!client)return;const{error}=await client.from('professionals').update({status}).eq('id',r.id);setMsg(error?`Erro: ${error.message}`:`${r.name}: ${status==='published'?'publicado':status==='archived'?'arquivado':'rascunho'} ✓`);if(!error)load()}
 async function remove(r:Row){const client=supabase;if(!client||!confirm(`Excluir definitivamente ${r.name}? Esta ação não pode ser desfeita.`))return;const{error}=await client.from('professionals').delete().eq('id',r.id);setMsg(error?`Erro: ${error.message}`:`${r.name} excluído ✓`);if(!error)load()}
 async function copy(r:Row){await navigator.clipboard.writeText(`${SITE_BASE}/${r.slug}`);setMsg(`URL de ${r.name} copiada ✓`)}
 const shown=useMemo(()=>rows.filter(r=>(filter==='all'||r.status===filter)&&(`${r.name} ${r.specialty||''} ${r.city||''}`.toLowerCase().includes(q.toLowerCase()))),[rows,q,filter]);
 const published=rows.filter(r=>r.status==='published').length,drafts=rows.filter(r=>r.status==='draft').length,archived=rows.filter(r=>r.status==='archived').length;
 if(!isSupabaseConfigured)return <main className="adminGenerator"><section className="adminIntro"><h1>Supabase não configurado.</h1></section></main>;
 if(loading)return <main className="adminGenerator"><section className="adminIntro"><p>Carregando clientes...</p></section></main>;
 if(!user)return <main className="adminGenerator"><section className="adminIntro"><div><h1>Acesso restrito.</h1><p>Entre primeiro pelo painel administrativo.</p><a href="/admin/novo-cliente">Entrar →</a></div></section></main>;
 return <main className="adminGenerator"><header className="adminTop"><div><b>37LAB</b><span>Sites</span></div><nav style={{display:'flex',gap:18,alignItems:'center'}}><a href="/admin/leads">Leads</a><a href="/admin/novo-cliente">Novo cliente</a><small>CLIENTES</small></nav></header><section className="adminIntro"><div><span className="adminKicker">CENTRAL DE CLIENTES</span><h1>{rows.length} sites<br/><em>sob seu controle.</em></h1><p>Edite conteúdo, publique, copie a URL comercial, conecte domínio próprio e arquive testes em um único lugar.</p></div><div className="adminStatus"><span>Publicados</span><b>{published}</b><span>Rascunhos</span><b>{drafts}</b><span>Arquivados</span><b>{archived}</b><span>{msg}</span></div></section><section style={{padding:'0 5vw 80px'}}><div style={{display:'grid',gridTemplateColumns:'minmax(220px,1fr) auto',gap:12,marginBottom:22}}><input aria-label="Buscar clientes" placeholder="Buscar por nome, especialidade ou cidade..." value={q} onChange={e=>setQ(e.target.value)} style={{padding:'15px 16px',border:'1px solid #ddd'}}/><select value={filter} onChange={e=>setFilter(e.target.value)} style={{padding:'0 16px',border:'1px solid #ddd'}}><option value="all">Todos</option><option value="published">Publicados</option><option value="draft">Rascunhos</option><option value="archived">Arquivados</option></select></div><div style={{display:'grid',gap:12}}>{shown.map(r=><article key={r.id} style={{background:'#fff',padding:22,border:'1px solid #e5e5e5',display:'grid',gridTemplateColumns:'minmax(0,1fr) auto',gap:18,alignItems:'center'}}><div><small>{r.template_key.toUpperCase()} • {r.status.toUpperCase()}</small><h2 style={{margin:'8px 0'}}>{r.name}</h2><p style={{margin:'0 0 8px'}}>{r.specialty||'Especialidade não informada'}{r.city?` • ${r.city}`:''}</p><code style={{fontSize:12}}>{SITE_BASE.replace('https://','')}/{r.slug}</code></div><div style={{display:'flex',gap:8,alignItems:'center',justifyContent:'flex-end',flexWrap:'wrap',maxWidth:520}}><a href={`/admin/clientes/${r.id}`}>Editar dados</a><a href={`/admin/clientes/${r.id}/conteudo`}>Conteúdo</a><a href={`/admin/clientes/${r.id}/dominio`}>Domínio</a><a href={`${SITE_BASE}/${r.slug}`} target="_blank" rel="noreferrer">Ver site ↗</a><button onClick={()=>copy(r)}>Copiar URL</button>{r.status==='published'?<button onClick={()=>setStatus(r,'draft')}>Despublicar</button>:<button onClick={()=>setStatus(r,'published')}>Publicar</button>}<button onClick={()=>setStatus(r,'archived')}>Arquivar</button>{r.status==='archived'&&<button onClick={()=>remove(r)}>Excluir</button>}</div></article>)}{shown.length===0&&<div style={{padding:40,background:'#fff',border:'1px solid #e5e5e5'}}><h3>Nenhum cliente encontrado.</h3><p>Ajuste a busca ou o filtro.</p></div>}</div></section></main>;
}
