import {NextRequest,NextResponse} from 'next/server';
export const maxDuration=20;
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const tokens=(s:string)=>norm(s).replace(/\b(dra?|dr)\.?\b/g,'').split(/[^a-z0-9]+/).filter(x=>x.length>2);
type R={url:string;title:string;snippet:string;engine:string;query:string;score?:number};
const clean=(s:string)=>s.replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();
function handle(url:string){try{const u=new URL(url);if(!/(^|\.)instagram\.com$/i.test(u.hostname))return'';const h=u.pathname.split('/').filter(Boolean)[0]||'';if(['p','reel','reels','stories','explore','accounts'].includes(h.toLowerCase()))return'';return /^[a-zA-Z0-9._]{3,30}$/.test(h)?h:''}catch{return''}}
async function bing(query:string):Promise<R[]>{try{const r=await fetch(`https://www.bing.com/search?format=rss&q=${encodeURIComponent(query)}`,{headers:{'User-Agent':'Mozilla/5.0','Accept':'application/rss+xml,text/xml'},cache:'no-store',signal:AbortSignal.timeout(4500)});if(!r.ok)return[];const xml=await r.text();return (xml.match(/<item>[\s\S]*?<\/item>/gi)||[]).map(item=>{const val=(tag:string)=>clean(item.match(new RegExp(`<${tag}>([\\s\\S]*?)<\\/${tag}>`,'i'))?.[1]||'');return{url:val('link'),title:val('title'),snippet:val('description'),engine:'bing',query}}).filter(x=>handle(x.url))}catch{return[]}}
async function duck(query:string):Promise<R[]>{try{const r=await fetch(`https://html.duckduckgo.com/html/?q=${encodeURIComponent(query)}`,{headers:{'User-Agent':'Mozilla/5.0'},cache:'no-store',signal:AbortSignal.timeout(4500)});if(!r.ok)return[];const html=await r.text();return html.split(/class="result\s/).slice(1).map(block=>{let url=block.match(/class="result__a"[^>]*href="([^"]+)"/i)?.[1]||'';try{const u=new URL(url.startsWith('//')?'https:'+url:url),d=u.searchParams.get('uddg');if(d)url=decodeURIComponent(d)}catch{}return{url,title:clean(block.match(/class="result__a"[^>]*>([\s\S]*?)<\/a>/i)?.[1]||''),snippet:clean(block.match(/class="result__snippet"[^>]*>([\s\S]*?)<\/(?:a|div)>/i)?.[1]||''),engine:'duckduckgo',query}}).filter(x=>handle(x.url))}catch{return[]}}
function score(r:R,name:string,specialty:string,city:string,state:string){const t=norm(`${r.title} ${r.snippet} ${r.url}`),nt=tokens(name),st=tokens(specialty);let s=0,hits=nt.filter(x=>t.includes(x)).length;if(nt.length&&hits===nt.length)s+=7;else if(hits>=Math.min(2,nt.length))s+=4;if(city&&t.includes(norm(city)))s+=5;if(state&&new RegExp(`\\b${norm(state)}\\b`).test(t))s+=1;if(st.some(x=>t.includes(x)))s+=3;const user=handle(r.url);if(user&&nt.some(x=>norm(user).includes(x)))s+=2;return s}
export async function POST(req:NextRequest){try{const b=await req.json(),name=String(b.name||'').trim(),specialty=String(b.specialty||'').trim(),city=String(b.city||'').trim(),state=String(b.state||'MG').trim();if(!name)return NextResponse.json({instagram:null,candidates:[]});const qs=[`site:instagram.com "${name}" "${city}"`,`site:instagram.com "${name}" ${specialty} ${city}`,`site:instagram.com "${name}" ${specialty} ${state}`,`Instagram "${name}" ${city} ${specialty}`,`"${name}" "Instagram" "${city}"`];const batches=await Promise.all(qs.map(async q=>[...(await bing(q)),...(await duck(q))]));const unique=[...new Map(batches.flat().map(x=>[handle(x.url),x])).values()].filter(x=>handle(x.url));const ranked=unique.map(x=>({...x,score:score(x,name,specialty,city,state)})).sort((a,b)=>(b.score||0)-(a.score||0));const nt=tokens(name);const strong=ranked.filter(x=>{const t=norm(`${x.title} ${x.snippet} ${x.url}`),hits=nt.filter(k=>t.includes(k)).length,nameMatch=nt.length>0&&hits>=Math.min(2,nt.length),cityMatch=!city||t.includes(norm(city)),specialtyMatch=!specialty||tokens(specialty).some(k=>t.includes(k));return (x.score||0)>=7&&nameMatch&&(cityMatch||specialtyMatch)});const top=strong[0];return NextResponse.json({instagram:top?`@${handle(top.url)}`:null,instagramUrl:top?.url||null,confidence:top?.score||0,candidates:ranked.slice(0,5).map(x=>({handle:`@${handle(x.url)}`,url:x.url,title:x.title,snippet:x.snippet,score:x.score,engine:x.engine})),queries:qs.length,requiresConfirmation:!top&&ranked.length>0})}catch(e:any){return NextResponse.json({error:e?.message||'Falha ao buscar Instagram'},{status:500})}}
