'use client';
import {useEffect,useState} from 'react';import{useRouter}from'next/navigation';
import {supabase} from '../../../lib/supabase';
type Failure={id:string;name:string;specialty?:string;city?:string;state?:string;error:string;attempts?:number;processedAt?:string|null};
type Stats={total:number;pending:number;ready:number;incomplete:number;no_result:number;conflict:number;failed:number;failures:Failure[]};
const empty:Stats={total:0,pending:0,ready:0,incomplete:0,no_result:0,conflict:0,failed:0,failures:[]};
export default function EnrichmentBar(){const router=useRouter(),[s,setS]=useState<Stats>(empty),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[showFailures,setShowFailures]=useState(false);async function authHeaders():Promise<Record<string,string>>{if(!supabase)return{};const{data}=await supabase.auth.getSession();return data.session?.access_token?{Authorization:`Bearer ${data.session.access_token}`}:{}}async function load(){try{const r=await fetch(`/api/enrich-professionals-queue?t=${Date.now()}`,{headers:await authHeaders(),cache:'no-store'});if(r.ok){const next={...empty,...await r.json()};setS(next);return next}}catch{}return null}useEffect(()=>{void load()},[]);
async function processQueue(){for(let i=0;i<80;i++){const r=await fetch('/api/enrich-professionals-queue',{method:'POST',headers:{'Content-Type':'application/json',...(await authHeaders())},body:'{}',cache:'no-store'}),text=await r.text();let x:any={};try{x=text?JSON.parse(text):{}}catch{x={error:`Resposta inválida (${r.status})`}}const stats=await load();if(!r.ok){setMessage(x.error||'Falha no processamento');break}if(x.done){setMessage(stats?`Busca concluída · ${stats.ready} completos · ${stats.incomplete+stats.conflict} com pendências · ${stats.failed} falhas`:'Busca concluída');router.refresh();break}await new Promise(ok=>setTimeout(ok,500))}}
async function run(force=false){if(busy)return;setBusy(true);setMessage(force?'Reiniciando os profissionais...':'Processando busca automática...');try{if(force){const total=s.total||117;setS({...empty,total,pending:total});const rr=await fetch('/api/enrich-professionals-queue',{method:'POST',headers:{'Content-Type':'application/json',...(await authHeaders())},body:JSON.stringify({reset:true}),cache:'no-store'}),text=await rr.text();let rx:any={};try{rx=text?JSON.parse(text):{}}catch{}if(!rr.ok||!rx.reset){setMessage(rx.error||'Não foi possível reiniciar a busca');await load();return}const checked=await load();if(!checked||checked.pending!==checked.total){setMessage(`A fila não foi reiniciada por completo (${checked?.pending||0}/${checked?.total||total}).`);return}setMessage(`Fila reiniciada: ${checked.total} profissionais aguardando. Iniciando nova busca...`)}await processQueue()}finally{setBusy(false);await load()}}
const done=s.ready+s.incomplete+s.no_result+s.conflict+s.failed,pct=s.total?Math.round(done/s.total*100):0,needs=s.incomplete+s.conflict;return <section className="enrichBar"><div className="enrichTitle"><b>Busca automática</b><span>{pct}%</span></div><div className="enrichTrack"><i style={{width:`${pct}%`}}/></div><div className="enrichNumbers">{done}/{s.total} pesquisados · {s.pending} aguardando · {s.ready} completos · {s.incomplete} incompletos · {s.no_result} sem resultado{s.conflict?` · ${s.conflict} conflitos`:''}{s.failed?` · ${s.failed} falhas`:''}</div>{message&&<small>{message}</small>}{needs>0&&<button className="enrichReview" onClick={()=>window.dispatchEvent(new Event('37lab:review'))}>Ver pendências ({needs})</button>}{s.failed>0&&<button className="enrichReview" onClick={()=>setShowFailures(v=>!v)}>{showFailures?'Ocultar falhas':`Ver falhas (${s.failed})`}</button>}<button className="enrichAction" onClick={()=>void run(false)} disabled={busy||!s.pending}>{busy?'Processando...':s.pending?'Alimentar':'Concluído ✓'}</button>{!s.pending&&s.total>0&&<button className="enrichReview" onClick={()=>void run(true)} disabled={busy}>{busy?'Reprocessando...':`Refazer busca nos ${s.total}`}</button>}{showFailures&&s.failures.length>0&&<div style={{width:'100%',marginTop:12,display:'grid',gap:8}}>{s.failures.map(f=><div key={f.id} style={{padding:'10px 12px',border:'1px solid rgba(120,120,120,.25)',borderRadius:8,textAlign:'left'}}><b>{f.name}</b>{f.specialty?` · ${f.specialty}`:''}{f.city?` · ${f.city}/${f.state||''}`:''}<div style={{marginTop:4,fontSize:12}}>Erro: {f.error}</div><div style={{marginTop:2,fontSize:11,opacity:.7}}>Tentativas registradas: {f.attempts||1}. A repetição automática foi bloqueada até corrigirmos a causa.</div></div>)}</div>}</section>}
