import './home.css';
export default function Home(){return <main className="sitesHome">
 <nav className="siteNav"><div className="siteLogo"><b>37LAB</b><span>Sites</span></div><a className="navCta" href="https://37lab.com.br">Conheça a 37LAB ↗</a></nav>
 <section className="homeHero">
  <div><span className="homeEyebrow">PRESENÇA DIGITAL PROFISSIONAL</span><h1>Seu trabalho merece um site <em>à altura.</em></h1><p className="homeLead">Criamos sites profissionais personalizados para transformar sua presença digital em uma apresentação clara, elegante e pronta para receber novos clientes.</p><div className="homeActions"><a className="homeButton" href="https://wa.me/5531993917212?text=Olá!%20Quero%20conhecer%20os%20sites%20da%2037LAB.">Quero meu site <span>→</span></a><a className="homeButton secondary" href="#como-funciona">Como funciona</a></div></div>
  <div className="previewStack" aria-hidden="true"><div className="previewCard back"><div className="fakeTop"><i/><i/><i/></div><div className="fakeBody"><small>SITE PROFISSIONAL</small><h3>Sua presença digital, organizada.</h3><p>Informações, serviços e contato em uma experiência única.</p><div className="fakePhoto"/></div></div><div className="previewCard main"><div className="fakeTop"><i/><i/><i/></div><div className="fakeBody"><small>37LAB SITES</small><h3>Feito para apresentar o seu trabalho.</h3><p>Design responsivo, conteúdo profissional e uma estrutura pensada para facilitar o contato com você.</p><div className="fakePhoto"/></div></div></div>
 </section>
 <section className="homeStrip"><div className="stripInner"><div><strong>Personalizado</strong><span>Identidade alinhada ao profissional</span></div><div><strong>Responsivo</strong><span>Perfeito no celular e computador</span></div><div><strong>Encontrável</strong><span>Estrutura preparada para o Google</span></div><div><strong>Direto</strong><span>Contato fácil por WhatsApp</span></div></div></section>
 <section className="homeSection" id="como-funciona"><div className="homeSectionHead"><div><span className="homeEyebrow">COMO FUNCIONA</span><h2>Do seu trabalho para a web.</h2></div><p>A 37LAB cuida da estrutura para você não precisar lidar com código, hospedagem ou detalhes técnicos. Organizamos sua apresentação profissional em um site que transmite confiança e facilita o próximo passo do cliente.</p></div><div className="featureGrid"><article className="feature"><span>01 — CONTEÚDO</span><h3>Organizamos sua presença.</h3><p>Apresentação, especialidades, serviços, localização, contatos e informações importantes em uma estrutura objetiva.</p></article><article className="feature"><span>02 — DESIGN</span><h3>Criamos sua experiência.</h3><p>Um visual profissional e contemporâneo, adaptado ao seu perfil e pensado primeiro para a experiência no celular.</p></article><article className="feature"><span>03 — PUBLICAÇÃO</span><h3>Colocamos seu site no ar.</h3><p>Depois da sua aprovação, cuidamos dos ajustes finais e deixamos tudo pronto para você divulgar seu endereço profissional.</p></article></div></section>
 <section className="finalCta"><span className="homeEyebrow">37LAB SITES</span><h2>Seu próximo cliente pode começar por aqui.</h2><p>Tenha um endereço profissional para apresentar seu trabalho, concentrar suas informações e facilitar o contato.</p><a className="homeButton" href="https://wa.me/5531993917212?text=Olá!%20Tenho%20interesse%20em%20um%20site%20profissional%20da%2037LAB.">Falar com a 37LAB →</a></section>
 <footer className="siteFooter"><span>© 37LAB — Produtos digitais e experiências para a web.</span><span>sites.37lab.com.br</span></footer>
 </main>}
