import {NextRequest,NextResponse} from 'next/server';
import {createClient} from '@supabase/supabase-js';
export const maxDuration=15;
const clean=(v:any)=>typeof v==='string'&&v.trim()?v.trim():'';
const hash=(s:string)=>Array.from(s).reduce((a,c)=>((a<<5)-a+c.charCodeAt(0))|0,0)>>>0;
const pick=<T,>(a:T[],seed:number,n=0)=>a[(seed+n)%a.length];
type CopyContentKey='hero_title'|'hero_emphasis'|'hero_description'|'about_title'|'about_body'|'quote'|'seo_title'|'seo_description';
const COPY_CONTENT_KEYS:CopyContentKey[]=['hero_title','hero_emphasis','hero_description','about_title','about_body','quote','seo_title','seo_description'];
const palettes=[
 {primary:'#17463d',secondary:'#78958c',background:'#f5f3ed',surface:'#ffffff'},
 {primary:'#173b57',secondary:'#7896a9',background:'#f3f6f7',surface:'#ffffff'},
 {primary:'#70453d',secondary:'#b08a7d',background:'#f8f2ee',surface:'#fffaf7'},
 {primary:'#5a496b',secondary:'#9a88a7',background:'#f6f2f7',surface:'#ffffff'},
 {primary:'#635333',secondary:'#aa9870',background:'#f7f4ec',surface:'#fffdf8'},
 {primary:'#243d42',secondary:'#78979a',background:'#f1f5f4',surface:'#ffffff'},
 {primary:'#6b3947',secondary:'#aa7d88',background:'#f8f2f4',surface:'#fffafb'},
 {primary:'#303638',secondary:'#8d9998',background:'#f4f4f1',surface:'#ffffff'}
];
function family(category:string,profession:string,specialty:string){const s=`${category} ${profession} ${specialty}`.toLowerCase();if(/odont|dent/.test(s))return'dental';if(/fisio/.test(s))return'physio';if(/clinic|clínic|laborat|centro/.test(s))return'clinic';if(/psic|nutri|fono|terap/.test(s))return'care';return'medical'}
function designFor(lead:any,seed:number){const raw=lead.raw_data||{},profession=clean(raw.profession)||clean(raw.professional_title),specialty=clean(lead.specialty)||clean(raw.specialty),f=family(lead.category||'',profession,specialty);const templates:Record<string,string[]>={dental:['dental-01','dental-02'],physio:['physio-01','care-01'],clinic:['clinic-01'],care:['care-01','medical-02'],medical:['medical-02','care-01']};const heroLayouts=['split','editorial','portrait','minimal','asymmetric'];return{template:pick(templates[f]||['medical-02'],seed,3),theme:pick(palettes,seed,9),heroLayout:pick(heroLayouts,seed,14),designFamily:f,variant:(seed%5)+1}}
function copyFor(lead:any){const raw=lead.raw_data||{},name=lead.name,profession=clean(raw.profession)||clean(raw.professional_title)||(lead.category==='dental'?'Dentista':lead.category==='physio'?'Fisioterapeuta':lead.category==='clinic'?'Clínica':'Profissional de saúde'),specialty=clean(lead.specialty)||clean(raw.specialty),area=specialty||profession,city=clean(lead.city)||clean(raw.city),state=clean(lead.state)||clean(raw.state),place=city?` em ${city}`:'',seed=hash(`${lead.id}|${name}|${area}`),f=family(lead.category||'',profession,specialty),en=raw.enrichment||{};
 const titles:Record<string,string[]>={dental:[`Odontologia pensada nos detalhes.`,`Seu sorriso, cuidado com precisão.`,`Cuidado odontológico com olhar individual.`,`Saúde e estética em equilíbrio.`,`Um novo olhar para o seu sorriso.`],physio:[`Movimento com propósito.`,`Cuidado para voltar ao que importa.`,`Movimento, função e qualidade de vida.`,`Seu corpo em movimento, com acompanhamento.`,`Cuidado que respeita o seu ritmo.`],care:[`Um espaço para cuidar de você.`,`Escuta, orientação e cuidado.`,`Cuidado construído com presença.`,`Atenção para cada fase da sua jornada.`,`Saúde com acolhimento e clareza.`],clinic:[`Cuidado reunido em um só lugar.`,`Uma experiência de saúde mais próxima.`,`Estrutura, cuidado e confiança.`,`Saúde com atendimento próximo.`,`Um espaço pensado para cuidar.`],medical:[`Medicina com atenção ao que importa.`,`Cuidado médico com olhar individual.`,`Saúde acompanhada de perto.`,`Conhecimento, escuta e acompanhamento.`,`Uma consulta que começa pela escuta.`]};
 const emphasis:Record<string,string[]>={dental:['Confiança para sorrir.','Precisão que acolhe.','Natural em cada detalhe.','Cuidado além da consulta.','Seu sorriso conta uma história.'],physio:['Evolução em cada movimento.','Respeito ao seu tempo.','Movimento é autonomia.','Cuidar também é recuperar confiança.','Cada conquista importa.'],care:['Cada história pede uma escuta.','Cuidado sem fórmulas prontas.','Presença faz diferença.','Seu processo, no seu tempo.','Acolher também é cuidar.'],clinic:['Tudo começa por um bom atendimento.','Cuidado do início ao fim.','Você no centro do atendimento.','Mais clareza. Mais proximidade.','Uma experiência feita para pessoas.'],medical:['Ciência com proximidade.','Escuta antes de tudo.','Cuidado que acompanha.','Clareza para cuidar melhor.','Atenção em cada decisão.']};
 const about:Record<string,string[]>={dental:['Sorrisos são únicos. O cuidado também deve ser.','Odontologia com planejamento e atenção individual.','Técnica e cuidado em cada etapa.'],physio:['Movimento é parte da sua história.','Um plano de cuidado para a sua realidade.','Acompanhamento para evoluir com segurança.'],care:['Cuidado começa quando existe espaço para ouvir.','Um atendimento construído a partir de você.','Acolhimento, orientação e acompanhamento.'],clinic:['Uma experiência de atendimento mais simples e próxima.','Estrutura para receber. Cuidado para acompanhar.','Um espaço pensado em cada etapa do atendimento.'],medical:['Cada pessoa traz uma história diferente.','Medicina feita com tempo para ouvir.','Informação e acompanhamento para decisões mais claras.']};
 const facts=[en.clinic||raw.clinic||raw.clinic_name,en.address||raw.address,en.registration||raw.registration].filter(Boolean);const factLine=facts.length?` ${facts.slice(0,2).join(' · ')}.`:'';const descriptions=[`${name} atua em ${area}${place}. O atendimento reúne orientação clara e acompanhamento individual, respeitando as necessidades de cada pessoa.${factLine}`,`${area}${place} com ${name}. Uma proposta de atendimento profissional, próxima e organizada em torno da realidade de cada paciente.${factLine}`,`${name} oferece atendimento em ${area}${place}, com uma abordagem individual e informações claras em cada etapa do cuidado.${factLine}`,`Atendimento em ${area}${place} com foco nas necessidades de cada pessoa. Conheça o trabalho de ${name} e os canais disponíveis para contato.${factLine}`];const bodies=[`${name} atua em ${area}${place}. As informações apresentadas aqui foram organizadas a partir dos dados profissionais disponíveis. Para detalhes sobre serviços, disponibilidade e modalidades de atendimento, consulte diretamente os canais de contato.`,`${name} desenvolve seu trabalho em ${area}${place}. A proposta deste espaço é reunir, de forma simples, as principais informações para quem procura conhecer o atendimento, localização e formas de contato.`,`Este é o espaço profissional de ${name}, com informações sobre atuação em ${area}${place}, localização e contato. Informações específicas sobre procedimentos e agenda devem ser confirmadas diretamente.`];const quotes=emphasis[f]||emphasis.medical;const d=designFor(lead,seed);return{hero_title:pick(titles[f]||titles.medical,seed),hero_emphasis:pick(emphasis[f]||emphasis.medical,seed,2),hero_description:clean(raw.bio)||pick(descriptions,seed,5),about_title:pick(about[f]||about.medical,seed,7),about_body:clean(raw.bio)||pick(bodies,seed,11),quote:pick(quotes,seed,13),seo_title:`${name} | ${area}${city?` em ${city}`:''}`,seo_description:`Conheça ${name}${specialty?`, ${specialty}`:''}${city?` em ${city}${state?`/${state}`:''}`:''}. Informações profissionais, localização e contato.`,generatedAt:new Date().toISOString(),source:'37lab-individual-copy-v4',design:d};}
export async function POST(req:NextRequest){try{const auth=req.headers.get('authorization'),url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key)return NextResponse.json({error:'Supabase não configurado'},{status:500});const client=createClient(url,key,{global:{headers:auth?{Authorization:auth}:{}}}),{data:{user}}=await client.auth.getUser();if(!user)return NextResponse.json({error:'Não autorizado'},{status:401});const body=await req.json().catch(()=>({})),regenerate=Boolean(body.regenerate);const{count:total}=await client.from('professional_leads').select('id',{count:'exact',head:true});let q=client.from('professional_leads').select('*').limit(25);if(!regenerate)q=q.is('raw_data->autoCopyV4',null);const{data:pending,error}=await q;if(error)throw error;if(!pending?.length)return NextResponse.json({total:total||0,processed:0,done:true,copyGenerated:0});let copyGenerated=0;for(const lead of pending){try{const raw=lead.raw_data||{},autoCopy=copyFor(lead);await client.from('professional_leads').update({raw_data:{...raw,autoCopyV4:autoCopy}}).eq('id',lead.id);copyGenerated++;if(lead.professional_id){const{data:p}=await client.from('professionals').select('*').eq('id',lead.professional_id).single();if(p){const patch:any={};for(const k of COPY_CONTENT_KEYS)patch[k]=autoCopy[k];patch.template_key=autoCopy.design.template;patch.content={...(p.content||{}),theme:autoCopy.design.theme,heroLayout:autoCopy.design.heroLayout,designFamily:autoCopy.design.designFamily,designVariant:autoCopy.design.variant,copyVersion:'37lab-individual-copy-v4'};await client.from('professionals').update(patch).eq('id',lead.professional_id)}}}catch{}}const done=pending.length<25;return NextResponse.json({total:total||0,processed:pending.length,done,copyGenerated});}catch(e:any){return NextResponse.json({error:e?.message||'Falha ao preparar conteúdo'},{status:500})}}
