import {NextRequest,NextResponse} from 'next/server';
import {createClient} from '@supabase/supabase-js';

export const maxDuration=30;
const clean=(v:any)=>typeof v==='string'&&v.trim()?v.trim():'';
const hash=(s:string)=>Array.from(s).reduce((a,c)=>((a<<5)-a+c.charCodeAt(0))|0,0)>>>0;
const pick=<T,>(a:T[],seed:number,n=0)=>a[(seed+n)%a.length];
function copyFor(lead:any){const raw=lead.raw_data||{},name=lead.name,profession=clean(raw.profession)||clean(raw.professional_title)||(lead.category==='dental'?'Dentista':lead.category==='physio'?'Fisioterapeuta':lead.category==='care'?'Profissional de saúde':lead.category==='clinic'?'Clínica':'Profissional de saúde'),specialty=clean(lead.specialty)||clean(raw.specialty),area=specialty||profession,city=clean(lead.city)||clean(raw.city),state=clean(lead.state)||clean(raw.state),place=city?` em ${city}`:'',seed=hash(`${lead.id}|${name}|${area}`);const ht=[`${area} com atendimento próximo e profissional`,`${area} com atenção individual para cada pessoa`,`${area} com cuidado pensado para você`,`${area} com atendimento humano e personalizado`],he=['Cuidado que começa pela escuta.','Atenção aos detalhes. Cuidado com você.','Um atendimento feito para a sua realidade.','Informação, cuidado e acompanhamento.'],hd=[`${name} atua em ${area}${place}, oferecendo atendimento profissional com atenção às necessidades de cada pessoa.`,`Atendimento em ${area}${place} com ${name}, reunindo acolhimento, orientação e atenção individual.`,`Conheça o trabalho de ${name} em ${area}${place}, com atendimento centrado na pessoa e em suas necessidades.`],at=['Cuidado profissional, de pessoa para pessoa.','Um atendimento construído com atenção.','Sobre o atendimento',`Conheça o trabalho de ${name}.`],ab=[`${name} atua na área de ${area}${place}. O atendimento é conduzido de forma individual, considerando as necessidades e o contexto de cada pessoa. Para informações sobre disponibilidade, modalidades de atendimento e agendamento, entre em contato diretamente.`,`${name} oferece atendimento em ${area}${place}. A proposta é proporcionar uma experiência profissional, acolhedora e clara, respeitando as particularidades de cada pessoa. Consulte os canais de contato para saber mais e agendar.`,`Com atuação em ${area}${place}, ${name} desenvolve um trabalho voltado ao atendimento individual e à orientação de cada pessoa de acordo com suas necessidades. Informações específicas sobre consultas e horários podem ser confirmadas diretamente.`],q=['Cuidar também é ouvir com atenção.','Cada cuidado começa com uma boa escuta.','Atenção individual faz parte de um bom atendimento.','Informação e cuidado caminham juntos.'];return{hero_title:pick(ht,seed),hero_emphasis:pick(he,seed,2),hero_description:clean(raw.bio)||pick(hd,seed,5),about_title:pick(at,seed,7),about_body:clean(raw.bio)||pick(ab,seed,11),quote:pick(q,seed,13),seo_title:`${name} | ${area}${city?` em ${city}`:''}`,seo_description:`Conheça ${name}${specialty?`, profissional de ${specialty}`:''}${city?` em ${city}${state?`/${state}`:''}`:''}. Informações de atendimento, localização e contato.`,generatedAt:new Date().toISOString(),source:'37lab-auto-copy-v2'};}
export async function POST(req:NextRequest){try{const auth=req.headers.get('authorization'),url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key)return NextResponse.json({error:'Supabase não configurado'},{status:500});const client=createClient(url,key,{global:{headers:auth?{Authorization:auth}:{}}}),{data:{user}}=await client.auth.getUser();if(!user)return NextResponse.json({error:'Não autorizado'},{status:401});const body=await req.json().catch(()=>({})),offset=Math.max(0,Number(body.offset)||0),limit=Math.min(50,Math.max(1,Number(body.limit)||10)),{data:rows,error}=await client.from('professional_leads').select('*').order('name').range(offset,offset+limit-1);if(error)throw error;let copyGenerated=0;for(const lead of rows||[]){try{const raw=lead.raw_data||{},autoCopy=raw.autoCopy||copyFor(lead);if(!raw.autoCopy){await client.from('professional_leads').update({raw_data:{...raw,autoCopy}}).eq('id',lead.id);copyGenerated++}if(lead.professional_id){const{data:p}=await client.from('professionals').select('*').eq('id',lead.professional_id).single();if(p){const patch:any={};for(const k of ['hero_title','hero_emphasis','hero_description','about_title','about_body','quote','seo_title','seo_description'])if((p[k]==null||p[k]==='')&&autoCopy[k])patch[k]=autoCopy[k];if(Object.keys(patch).length)await client.from('professionals').update(patch).eq('id',lead.professional_id)}}}catch{}}
const{count}=await client.from('professional_leads').select('id',{count:'exact',head:true}),nextOffset=offset+(rows?.length||0);return NextResponse.json({total:count||0,offset,processed:rows?.length||0,nextOffset,done:nextOffset>=(count||0),enriched:0,copyGenerated});}catch(e:any){return NextResponse.json({error:e?.message||'Falha ao preparar conteúdo'},{status:500})}}
