import {supabase} from './supabase';import{suggestTemplate}from'./template-router';
export type DemoResult={leadId:string;professionalId?:string;slug?:string;created:boolean;error?:string};
const slugify=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/^(dr|dra)\.?\s+/,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const splitReg=(v?:string|null)=>{if(!v)return{label:null,number:null};const parts=v.split('|').map(x=>x.trim());const m=parts[0].match(/^([A-Za-z-]+)\s*(.*)$/);return{label:m?.[1]||null,number:[m?.[2],...parts.slice(1)].filter(Boolean).join(' | ')||null}};
async function uniqueSlug(base:string){if(!supabase)return base;let slug=base||'profissional';let n=2;while(true){const{data}=await supabase.from('professionals').select('id').eq('slug',slug).maybeSingle();if(!data)return slug;slug=`${base}-${n++}`}}
export async function generateDemoForLead(leadId:string):Promise<DemoResult>{
 const client=supabase;if(!client)return{leadId,created:false,error:'Supabase não configurado'};
 const[{data:lead,error:le},{data:facts,error:fe}]=await Promise.all([client.from('professional_leads').select('*').eq('id',leadId).single(),client.from('enrichment_facts').select('*').eq('lead_id',leadId).eq('verified',true)]);
 if(le||!lead)return{leadId,created:false,error:le?.message||'Lead não encontrado'};if(fe)return{leadId,created:false,error:fe.message};if(lead.professional_id)return{leadId,professionalId:lead.professional_id,created:false,error:'Demo já vinculada'};
 const f=(name:string)=>facts?.find((x:any)=>x.field_name===name)?.field_value||null;const raw=lead.raw_data||{};const registration=f('registration')||raw.registration||null;const reg=splitReg(registration);const specialty=f('specialty')||lead.specialty||raw.specialty||'';const clinic=f('clinic')||f('clinic_name')||raw.clinic||null;const address=f('address')||raw.address||null;const phone=f('phone')||raw.phone||null;const whatsapp=f('whatsapp')||raw.whatsapp||null;const profession=f('professional_title')||raw.profession||(lead.category==='dental'?'Dentista':lead.category==='physio'?'Fisioterapeuta':lead.category==='care'?'Profissional de saúde':lead.category==='clinic'?'Clínica':'Médico');const servicesText=f('services')||'';const services=servicesText.split(';').map((x:string)=>x.trim()).filter(Boolean).slice(0,6);const slug=await uniqueSlug(slugify(lead.name));const template=lead.suggested_template||suggestTemplate(lead.category||'',specialty,lead.name);const bio=f('bio')||`${profession}${specialty?` com atuação em ${specialty}`:''}${lead.city?` em ${lead.city}`:''}.`;
 const payload={slug,status:'draft',template_key:template,category:lead.category||'medical',name:lead.name,professional_title:profession,registration_label:reg.label,registration_number:reg.number,specialty:specialty||null,city:lead.city||null,state:lead.state||null,whatsapp:whatsapp?String(whatsapp).replace(/\D/g,''):null,phone,address,clinic_name:clinic,hero_description:bio,seo_title:`${lead.name} | ${specialty||profession}${lead.city?` em ${lead.city}`:''}`,seo_description:`Informações profissionais de ${lead.name}${specialty?`, ${specialty}`:''}${lead.city?` em ${lead.city}/${lead.state||''}`:''}.`,content:{instagram:f('instagram')||raw.instagram||null,sourceLeadId:leadId,generatedFromVerifiedFacts:true,prospectingDemo:true}};
 const{data:p,error:pe}=await client.from('professionals').insert(payload).select('id,slug').single();if(pe)return{leadId,created:false,error:pe.message};
 if(services.length){const{error}=await client.from('professional_services').insert(services.map((title:string,i:number)=>({professional_id:p.id,title,description:'',icon:'plus',position:i})));if(error)return{leadId,professionalId:p.id,slug:p.slug,created:true,error:`Demo criada, serviços pendentes: ${error.message}`}}
 const faqs=[{question:'Como funciona o atendimento?',answer:'Entre em contato para confirmar formato, disponibilidade e orientações para o atendimento.'},{question:'Como agendar?',answer:'O agendamento e as informações de disponibilidade podem ser confirmados diretamente com o profissional ou equipe.'},{question:'Onde acontece o atendimento?',answer:address?`O atendimento informado está localizado em ${address}. Confirme os detalhes no momento do agendamento.`:'Confirme o local e a modalidade de atendimento diretamente com o profissional.'}];await client.from('professional_faqs').insert(faqs.map((x,i)=>({professional_id:p.id,...x,position:i})));
 const{error:linkError}=await client.from('professional_leads').update({commercial_status:'demo_ready',enrichment_status:'complete',professional_id:p.id}).eq('id',leadId);if(linkError)return{leadId,professionalId:p.id,slug:p.slug,created:true,error:`Demo criada, vínculo pendente: ${linkError.message}`};return{leadId,professionalId:p.id,slug:p.slug,created:true}
}
export async function generateReadyDemos(){const client=supabase;if(!client)return[];const{data}=await client.from('professional_leads').select('id').eq('commercial_status','demo_ready').is('professional_id',null).order('confidence',{ascending:false});const out:DemoResult[]=[];for(const lead of data||[])out.push(await generateDemoForLead(lead.id));return out;}
