import {supabase} from './supabase';import{suggestTemplate}from'./template-router';
export type DemoResult={leadId:string;professionalId?:string;slug?:string;created:boolean;error?:string};
const slugify=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/^(dr|dra)\.?\s+/,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const splitReg=(v?:string|null)=>{if(!v)return{label:null,number:null};const parts=v.split('|').map(x=>x.trim());const m=parts[0].match(/^([A-Za-z-]+)\s*(.*)$/);return{label:m?.[1]||null,number:[m?.[2],...parts.slice(1)].filter(Boolean).join(' | ')||null}};
const hash=(s:string)=>Array.from(s).reduce((a,c)=>((a<<5)-a+c.charCodeAt(0))|0,0)>>>0;
const pick=<T,>(items:T[],seed:number,offset=0)=>items[(seed+offset)%items.length];
const clean=(v:any)=>typeof v==='string'&&v.trim()?v.trim():null;
function generatedCopy(name:string,profession:string,specialty:string,city:string,seed:number){
 const area=specialty||profession;const place=city?` em ${city}`:'';
 const heroTitles=[`${area} com atendimento próximo e profissional`,`${area} para cuidar de você em cada etapa`,`${area} com atenção, escuta e cuidado`,`${area} com um olhar individual para cada pessoa`,`${area} com cuidado pensado para você`,`${area} com atendimento humano e personalizado`];
 const heroEmphasis=[`Cuidado que começa pela escuta.`,`Atenção aos detalhes. Cuidado com você.`,`Sua saúde merece atenção individual.`,`Um atendimento feito para a sua realidade.`,`Informação, cuidado e acompanhamento.`,`Cada pessoa merece um cuidado único.`];
 const descriptions=[`${name} atua em ${area}${place}, oferecendo atendimento profissional com atenção às necessidades de cada pessoa.`,`${name} oferece atendimento em ${area}${place}, com uma abordagem cuidadosa, clara e individualizada.`,`Atendimento em ${area}${place} com ${name}, reunindo acolhimento, orientação e atenção individual.`,`${name} trabalha com ${area}${place}, valorizando uma relação próxima e um atendimento pensado para cada necessidade.`,`Conheça o trabalho de ${name} em ${area}${place}, com atendimento centrado na pessoa e em suas necessidades.`,`Em ${area}${place}, ${name} oferece um atendimento profissional pautado em escuta, cuidado e acompanhamento individual.`];
 const aboutTitles=[`Cuidado profissional, de pessoa para pessoa.`,`Um atendimento construído com atenção.`,`Sobre o atendimento`,`Experiência e cuidado em cada encontro.`,`Atenção individual em cada etapa.`,`Conheça o trabalho de ${name}.`];
 const aboutBodies=[`${name} atua na área de ${area}${place}. O atendimento é conduzido de forma individual, considerando as necessidades e o contexto de cada pessoa. Para informações sobre disponibilidade, modalidades de atendimento e agendamento, entre em contato diretamente.`,`${name} oferece atendimento em ${area}${place}. A proposta é proporcionar uma experiência profissional, acolhedora e clara, respeitando as particularidades de cada pessoa. Consulte os canais de contato para saber mais e agendar.`,`Com atuação em ${area}${place}, ${name} desenvolve um trabalho voltado ao atendimento individual e à orientação de cada pessoa de acordo com suas necessidades. Informações específicas sobre consultas e horários podem ser confirmadas diretamente.`,`O trabalho de ${name} é dedicado à ${area}${place}, com atenção individual e comunicação clara durante o atendimento. Entre em contato para conhecer as modalidades disponíveis, horários e demais informações.`,`Na atuação em ${area}${place}, ${name} busca oferecer um atendimento próximo e organizado, considerando as necessidades apresentadas em cada caso. Para detalhes sobre agenda e funcionamento, utilize os canais de contato.`,`${name} atua profissionalmente em ${area}${place}, oferecendo atendimento individualizado e orientação dentro de sua área de atuação. Consulte diretamente o profissional ou a equipe para informações sobre agenda e atendimento.`];
 const quotes=[`Cuidar também é ouvir com atenção.`,`Cada cuidado começa com uma boa escuta.`,`Atenção individual faz parte de um bom atendimento.`,`Informação e cuidado caminham juntos.`,`Um bom atendimento começa entendendo cada pessoa.`,`Cuidado é também presença, atenção e orientação.`];
 return{hero_title:pick(heroTitles,seed),hero_emphasis:pick(heroEmphasis,seed,3),hero_description:pick(descriptions,seed,7),about_title:pick(aboutTitles,seed,11),about_body:pick(aboutBodies,seed,17),quote:pick(quotes,seed,23)};
}
async function uniqueSlug(base:string){if(!supabase)return base;let slug=base||'profissional';let n=2;while(true){const{data}=await supabase.from('professionals').select('id').eq('slug',slug).maybeSingle();if(!data)return slug;slug=`${base}-${n++}`}}
export async function generateDemoForLead(leadId:string):Promise<DemoResult>{
 const client=supabase;if(!client)return{leadId,created:false,error:'Supabase não configurado'};
 const[{data:lead,error:le},{data:facts,error:fe}]=await Promise.all([client.from('professional_leads').select('*').eq('id',leadId).single(),client.from('enrichment_facts').select('*').eq('lead_id',leadId).eq('verified',true)]);
 if(le||!lead)return{leadId,created:false,error:le?.message||'Lead não encontrado'};if(fe)return{leadId,created:false,error:fe.message};if(lead.professional_id)return{leadId,professionalId:lead.professional_id,created:false,error:'Demo já vinculada'};
 const f=(name:string)=>clean(facts?.find((x:any)=>x.field_name===name)?.field_value);const raw=lead.raw_data||{};const registration=f('registration')||clean(raw.registration);const reg=splitReg(registration);const specialty=f('specialty')||clean(lead.specialty)||clean(raw.specialty)||'';const clinic=f('clinic')||f('clinic_name')||clean(raw.clinic)||clean(raw.clinic_name);const address=f('address')||clean(raw.address);const phone=f('phone')||clean(raw.phone)||clean(raw.telephone);const whatsapp=f('whatsapp')||clean(raw.whatsapp)||phone;const profession=f('professional_title')||clean(raw.profession)||(lead.category==='dental'?'Dentista':lead.category==='physio'?'Fisioterapeuta':lead.category==='care'?'Profissional de saúde':lead.category==='clinic'?'Clínica':'Médico');const servicesText=f('services')||clean(raw.services)||'';const services=servicesText.split(';').map((x:string)=>x.trim()).filter(Boolean).slice(0,6);const slug=await uniqueSlug(slugify(lead.name));const template=lead.suggested_template||suggestTemplate(lead.category||'',specialty,lead.name);const city=clean(lead.city)||clean(raw.city)||'';const state=clean(lead.state)||clean(raw.state)||'';const copy=generatedCopy(lead.name,profession,specialty,city,hash(`${lead.id}|${lead.name}|${specialty}`));const bio=f('bio')||clean(raw.bio);const instagram=f('instagram')||clean(raw.instagram);const website=f('website')||clean(raw.website);
 const payload={slug,status:'draft',template_key:template,category:lead.category||'medical',name:lead.name,professional_title:profession,registration_label:reg.label,registration_number:reg.number,specialty:specialty||null,city:city||null,state:state||null,whatsapp:whatsapp?String(whatsapp).replace(/\D/g,''):null,phone,address,clinic_name:clinic,hero_title:copy.hero_title,hero_emphasis:copy.hero_emphasis,hero_description:bio||copy.hero_description,about_title:copy.about_title,about_body:bio||copy.about_body,quote:copy.quote,seo_title:`${lead.name} | ${specialty||profession}${city?` em ${city}`:''}`,seo_description:`Conheça ${lead.name}${specialty?`, profissional de ${specialty}`:''}${city?` em ${city}${state?`/${state}`:''}`:''}. Informações de atendimento, localização e contato.`,content:{instagram,website,sourceLeadId:leadId,generatedFromVerifiedFacts:true,prospectingDemo:true,copyVariant:hash(`${lead.id}|${lead.name}|${specialty}`)%1000}};
 const{data:p,error:pe}=await client.from('professionals').insert(payload).select('id,slug').single();if(pe)return{leadId,created:false,error:pe.message};
 if(services.length){const{error}=await client.from('professional_services').insert(services.map((title:string,i:number)=>({professional_id:p.id,title,description:'',icon:'plus',position:i})));if(error)return{leadId,professionalId:p.id,slug:p.slug,created:true,error:`Demo criada, serviços pendentes: ${error.message}`}}
 const faqs=[{question:'Como funciona o atendimento?',answer:`Para informações sobre o atendimento de ${lead.name}, entre em contato para confirmar formato, disponibilidade e orientações.`},{question:'Como faço para agendar?',answer:'O agendamento e os horários disponíveis podem ser confirmados diretamente pelos canais de contato informados no site.'},{question:'Onde acontece o atendimento?',answer:address?`O endereço informado é ${address}. Confirme os detalhes no momento do agendamento.`:'O local e a modalidade de atendimento podem ser confirmados diretamente com o profissional ou equipe.'}];await client.from('professional_faqs').insert(faqs.map((x,i)=>({professional_id:p.id,...x,position:i})));
 const{error:linkError}=await client.from('professional_leads').update({commercial_status:'demo_ready',enrichment_status:'complete',professional_id:p.id}).eq('id',leadId);if(linkError)return{leadId,professionalId:p.id,slug:p.slug,created:true,error:`Demo criada, vínculo pendente: ${linkError.message}`};return{leadId,professionalId:p.id,slug:p.slug,created:true}
}
export async function generateReadyDemos(){const client=supabase;if(!client)return[];const{data}=await client.from('professional_leads').select('id').eq('commercial_status','demo_ready').is('professional_id',null).order('confidence',{ascending:false});const out:DemoResult[]=[];for(const lead of data||[])out.push(await generateDemoForLead(lead.id));return out;}
