import { notFound } from 'next/navigation';
import { getProfessional } from '../../../lib/professionals';

const Icon=({type}:{type:string})=>{const icons:Record<string,string>={heart:'♡',shield:'◇',user:'♙',plus:'✦',pin:'⌖',phone:'☎',instagram:'◎',arrow:'↗'};return <span className="icon">{icons[type]||'✦'}</span>};

export default async function DemoPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params; const p=getProfessional(slug); if(!p) notFound();
 const mapQuery=encodeURIComponent([p.clinic,p.address].filter(Boolean).join(' '));
 return <main>
  <div className="demoBar"><span>CONCEITO 37LAB</span><b>Demonstração privada</b><span>NÃO INDEXADA</span></div>
  <header className="siteHeader"><a className="brand" href="#inicio"><span className="brandMark">✦</span><span><strong>{p.shortName}</strong><small>{p.specialty}</small></span></a><nav className="navLinks"><a href="#sobre">Sobre</a><a href="#servicos">Atuação</a><a href="#local">Local</a><a href="#faq">Dúvidas</a></nav><a className="headerCta" href="#contato">Agendar <span>↗</span></a></header>
  <section id="inicio" className="hero"><div className="heroCopy"><div className="eyebrow">SAÚDE • ESCUTA • PREVENÇÃO</div><h1>Cuidado próximo.<br/><em>Saúde por inteiro.</em></h1><p>{p.bio}</p><div className="heroActions">{p.whatsapp&&<a className="primary" href={`https://wa.me/${p.whatsapp}`} target="_blank">Agendar pelo WhatsApp <span>↗</span></a>}<a className="secondary" href="#sobre">Conheça a abordagem</a></div><div className="trustRow"><div><Icon type="user"/><span><b>Atendimento</b>individualizado</span></div><div><Icon type="shield"/><span><b>Prevenção</b>cuidado contínuo</span></div><div><Icon type="heart"/><span><b>Acompanhamento</b>humanizado</span></div></div></div><div className="heroVisual"><div className="photoPlaceholder"><div className="photoMonogram">{p.shortName.split(' ').slice(1,3).map(x=>x[0]).join('')}</div><span>Foto profissional do cliente</span></div><div className="doctorCard"><small>{p.profession}</small><strong>{p.name}</strong><span>{p.registration}</span></div><div className="visualBadge">Piumhi • MG</div></div></section>
  <section id="sobre" className="about"><div className="aboutVisual"><div className="consultPlaceholder"><Icon type="plus"/><span>Imagem de atendimento / consultório</span></div><div className="aboutStat"><strong>01</strong><span>cuidado centrado<br/>em cada paciente</span></div></div><div className="aboutCopy"><div className="eyebrow">SOBRE O PROFISSIONAL</div><h2>Medicina com escuta,<br/>ciência e humanidade.</h2><p>{p.bio}</p><p>A proposta é construir uma relação de confiança, com atenção à prevenção, ao acompanhamento e às necessidades individuais de cada paciente.</p><blockquote>“Cuidar da saúde também é acompanhar, orientar e prevenir.”</blockquote><div className="credentials"><span><Icon type="plus"/><b>{p.profession}</b></span>{p.registration&&<span><Icon type="shield"/><b>{p.registration}</b></span>}<span><Icon type="heart"/><b>Cuidado humanizado</b></span></div></div></section>
  <section id="servicos" className="services"><div className="sectionIntro"><div className="eyebrow">PRINCIPAIS ÁREAS DE ATUAÇÃO</div><h2>Como posso te ajudar?</h2><p>Uma jornada de cuidado pensada para prevenção, orientação e acompanhamento.</p></div><div className="cards">{p.services.map((s,i)=><article key={s.title}><span className="cardNumber">0{i+1}</span><Icon type={i%2?'heart':'plus'}/><h3>{s.title}</h3><p>{s.description}</p><span className="cardArrow">↗</span></article>)}</div></section>
  {(p.clinic||p.address)&&<section id="local" className="location"><div className="locationMedia"><div className="clinicPlaceholder"><span>Imagem da clínica / consultório</span></div></div><div className="locationCopy"><div className="eyebrow">ONDE ATENDO</div><h2>{p.clinic}</h2>{p.address&&<p className="locationLine"><Icon type="pin"/>{p.address}</p>}{p.phone&&<p className="locationLine"><Icon type="phone"/>{p.phone}</p>}<a className="mapButton" href={`https://www.google.com/maps/search/?api=1&query=${mapQuery}`} target="_blank">Ver localização <span>↗</span></a></div><div className="mapMock"><div className="mapGrid"></div><div className="mapPin">●</div><span>Mapa</span></div></section>}
  <section id="faq" className="faq"><div><div className="eyebrow">DÚVIDAS FREQUENTES</div><h2>Antes da consulta</h2><p>Algumas informações podem ser confirmadas diretamente com a equipe no momento do agendamento.</p></div><div className="faqList"><details><summary>Como faço para agendar?<span>+</span></summary><p>Entre em contato pelo WhatsApp e consulte os horários disponíveis.</p></details><details><summary>Onde acontece o atendimento?<span>+</span></summary><p>{p.clinic}{p.address?` — ${p.address}`:''}.</p></details><details><summary>Atende por convênio?<span>+</span></summary><p>Consulte diretamente a equipe para confirmar convênios e modalidades de atendimento.</p></details><details><summary>Como funciona a primeira consulta?<span>+</span></summary><p>As orientações específicas são fornecidas no momento do agendamento.</p></details></div></section>
  <section id="contato" className="cta"><div><div className="eyebrow">VAMOS CUIDAR DA SUA SAÚDE?</div><h2>Seu cuidado começa<br/>com uma conversa.</h2><p>Entre em contato para consultar disponibilidade e informações de atendimento.</p></div>{p.whatsapp&&<a href={`https://wa.me/${p.whatsapp}`} target="_blank">Agendar pelo WhatsApp <span>↗</span></a>}</section>
  <footer><div className="footerBrand"><strong>{p.shortName}</strong><span>{p.specialty}</span></div><div className="footerNav"><a href="#sobre">Sobre</a><a href="#servicos">Atuação</a><a href="#local">Local</a><a href="#faq">Dúvidas</a></div><div className="footerSocial">{p.instagram&&<a href={p.instagram}><Icon type="instagram"/></a>}{p.whatsapp&&<a href={`https://wa.me/${p.whatsapp}`}><Icon type="phone"/></a>}</div><div className="footerBottom"><span>© {new Date().getFullYear()} {p.name}</span><span>Conceito e tecnologia <b>37LAB</b></span></div></footer>
 </main>
}