import {NextRequest,NextResponse} from 'next/server';
import {createClient} from '@supabase/supabase-js';
export const maxDuration=30;
const clean=(v:any)=>typeof v==='string'&&v.trim()?v.trim():null;
async function readJson(r:Response){const t=await r.text();try{return t?JSON.parse(t):{}}catch{return{}}}
export async function POST(req:NextRequest){try{
 const auth=req.headers.get('authorization'),url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
 if(!url||!key)return NextResponse.json({error:'Supabase não configurado'},{status:500});
 const client=createClient(url,key,{global:{headers:auth?{Authorization:auth}:{}}}),{data:{user}}=await client.auth.getUser();if(!user)return NextResponse.json({error:'Não autorizado'},{status:401});
 const{id}=await req.json();const{data:p,error}=await client.from('professionals').select('*').eq('id',id).single();if(error||!p)return NextResponse.json({error:'Site não encontrado'},{status:404});
 const content=p.content||{};let lead:any=null;if(content.sourceLeadId){const{data}=await client.from('professional_leads').select('*').eq('id',content.sourceLeadId).maybeSingle();lead=data}
 const raw=lead?.raw_data||{},old=raw.enrichment||{},identity={name:p.name,city:p.city||lead?.city||'',state:p.state||lead?.state||'MG',specialty:p.specialty||p.professional_title||lead?.specialty||''};let found:any={},ig:any={};let searchError='';
 try{const origin=new URL(req.url).origin,[a,b]=await Promise.all([fetch(`${origin}/api/enrich-professional`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(identity),cache:'no-store',signal:AbortSignal.timeout(24000)}),fetch(`${origin}/api/find-professional-instagram`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(identity),cache:'no-store',signal:AbortSignal.timeout(24000)})]);found=await readJson(a);ig=await readJson(b);if(!a.ok)searchError=found.error||`Busca ${a.status}`}catch(e:any){searchError=e?.message||'Falha na busca'}
 // Prefer fresh verified search results for fields the user explicitly asked us to discover.
 // Existing values remain the fallback, so a failed search never erases data.
 const address=clean(found.address)||clean(old.address)||clean(p.address),clinic=clean(found.clinic)||clean(old.clinic)||clean(p.clinic_name),phone=clean(found.phone)||clean(old.phone)||clean(p.phone),whatsapp=clean(found.whatsapp)||clean(old.whatsapp)||clean(p.whatsapp)||phone,instagram=clean(ig.instagram)||clean(found.instagram)||clean(old.instagram)||clean(content.instagram);
 const registration=clean(found.registration)||clean(old.registration)||clean(p.registration_number);
 const sources=Array.isArray(found.sources)?found.sources:[];if(ig.instagramUrl&&!sources.some((x:any)=>x.url===ig.instagramUrl))sources.push({url:ig.instagramUrl,title:`Instagram ${ig.instagram}`,engine:'instagram-discovery',identityScore:ig.confidence||0});
 const candidates=Array.isArray(found.photoCandidates)?found.photoCandidates:[],locationCandidates=Array.isArray(found.locationPhotoCandidates)?found.locationPhotoCandidates:[],facts={...(old.facts||{}),...(found.facts||{}),registration:registration||null,address:address||null,clinic:clinic||null,phone:phone||null,whatsapp:whatsapp||null,instagram:instagram||null,updatedAt:new Date().toISOString()};
 const diagnostics={phone:Boolean(phone),whatsapp:Boolean(whatsapp),instagram:Boolean(instagram),address:Boolean(address),clinic:Boolean(clinic),photo:Boolean(candidates.length||content.photoWorkflow?.identityConfirmed),locationPhoto:Boolean(locationCandidates.length||content.locationPhotoWorkflow?.locationConfirmed),sources:sources.length,verifiedPages:found.diagnostics?.verifiedPages||0,queries:(found.diagnostics?.queries||0)+(ig.queries||0),searchError:searchError||null};
 const patch:any={content:{...content,instagram:instagram||'',verifiedFacts:facts,enrichmentSources:sources,enrichmentDiagnostics:diagnostics,photoCandidates:candidates.length?candidates:content.photoCandidates||[],locationPhotoCandidates:locationCandidates.length?locationCandidates:content.locationPhotoCandidates||[],photoWorkflow:candidates.length&&!content.photoWorkflow?.identityConfirmed?{status:'awaiting_identity_confirmation',candidateCount:candidates.length,rule:'real_photo_only',targetStyle:'white_background_standardized_full_subject_no_crop'}:content.photoWorkflow,locationPhotoWorkflow:locationCandidates.length&&!content.locationPhotoWorkflow?.locationConfirmed?{status:'awaiting_location_confirmation',candidateCount:locationCandidates.length,rule:'real_location_only_prefer_facade',priority:['facade','building_entrance','real_interior','clinic_logo','none']}:content.locationPhotoWorkflow,lastOnDemandEnrichment:new Date().toISOString()}};
 if(address)patch.address=address;if(clinic)patch.clinic_name=clinic;if(phone)patch.phone=phone;if(whatsapp)patch.whatsapp=String(whatsapp).replace(/\D/g,'');
 if(registration){const m=String(registration).match(/^([A-Za-z-]+)\s*(.*)$/);if(found.registration||!p.registration_number){patch.registration_label=m?.[1]||p.registration_label||null;patch.registration_number=m?.[2]||registration}}
 const{error:ue}=await client.from('professionals').update(patch).eq('id',id);if(ue)throw ue;
 if(lead?.id)await client.from('professional_leads').update({raw_data:{...raw,enrichment:{...old,...facts,sources}}}).eq('id',lead.id);
 return NextResponse.json({ok:true,found:Boolean(address||clinic||phone||whatsapp||instagram||candidates.length),address,clinic,phone,whatsapp,instagram,registration:registration||'',photoCandidates:candidates,locationPhotoCandidates:locationCandidates,diagnostics,sources,facts})
}catch(e:any){return NextResponse.json({error:e?.message||'Falha ao buscar dados'},{status:500})}}
