import {NextRequest,NextResponse} from 'next/server';

const ALLOWED=['doctoralia.com.br','psitto.com.br'];
const clean=(s:string)=>s.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const absolute=(href:string)=>href.startsWith('//')?`https:${href}`:href;
function registration(text:string){return text.match(/\b(?:CRP|CRM|CRO|CREFITO|CRN|COREN|CRF|CFP)(?:[-\s]?(?:MG|SP|RJ|ES))?\s*(?:N[º°]?\s*)?[\d./-]{3,}\b/i)?.[0]||''}
function address(text:string,city:string){const cityEsc=city.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const re=new RegExp(`((?:Rua|R\\.|Avenida|Av\\.|Praça|Pça\\.|Alameda|Travessa)\\s+[^|•]{3,90}?(?:\\d{1,5})[^|•]{0,45}?(?:${cityEsc}|MG))`,'i');return text.match(re)?.[1]?.replace(/\s+(Mapa|Consultório|Atende).*$/i,'').trim()||''}
function clinic(text:string,name:string){const n=norm(name);const chunks=text.split(/\s{2,}|[|•]/).map(x=>x.trim()).filter(Boolean);return chunks.find(x=>{const y=norm(x);return x.length<100&&(y.includes('consultorio')||y.includes('clinica'))&&!y.includes(n)})||''}
function meta(html:string,key:string){const esc=key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const a=html.match(new RegExp(`<meta[^>]+(?:property|name)=["']${esc}["'][^>]+content=["']([^"']+)["']`,'i'))?.[1];const b=html.match(new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${esc}["']`,'i'))?.[1];return (a||b||'').replace(/&amp;/g,'&')}
async function search(query:string){const url=`https://html.duckduckgo.com/html/?q=${encodeURIComponent(query)}`;const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 37LAB-Sites/1.0'},cache:'no-store'});if(!r.ok)return[];const html=await r.text();const links=[...html.matchAll(/class="result__a"[^>]*href="([^"]+)"/g)].map(m=>absolute(m[1])).map(u=>{try{const x=new URL(u);const target=x.searchParams.get('uddg');return target?decodeURIComponent(target):u}catch{return u}});return links.filter(u=>{try{return ALLOWED.some(d=>new URL(u).hostname.endsWith(d))}catch{return false}}).slice(0,4)}
async function page(url:string){try{const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 37LAB-Sites/1.0'},redirect:'follow',cache:'no-store',signal:AbortSignal.timeout(6000)});if(!r.ok)return null;const html=await r.text();return{html,text:clean(html)}}catch{return null}}
export async function POST(req:NextRequest){try{const body=await req.json();const name=String(body.name||'').trim(),city=String(body.city||'').trim(),state=String(body.state||'MG').trim();if(!name)return NextResponse.json({error:'Nome obrigatório'},{status:400});const urls=await search(`"${name}" ${city} ${state} psicólogo médico dentista nutricionista fisioterapeuta Doctoralia`);const docs=(await Promise.all(urls.map(async url=>({url,page:await page(url)})))).filter(x=>x.page?.text&&norm(x.page.text).includes(norm(name).split(' ').slice(0,2).join(' ')));let reg='',addr='',cl='';const photoCandidates:any[]=[];for(const d of docs){const text=d.page!.text,html=d.page!.html;reg=reg||registration(text);addr=addr||address(text,city);cl=cl||clinic(text,name);const image=meta(html,'og:image'),title=meta(html,'og:title');if(image&&/^https?:\/\//i.test(image)&&!photoCandidates.some(x=>x.url===image))photoCandidates.push({url:image,source:d.url,title:title||name,verifiedNameMatch:true})}return NextResponse.json({registration:reg,address:addr,clinic:cl,sources:docs.map(x=>x.url),photoCandidates:photoCandidates.slice(0,3),found:Boolean(reg||addr||cl||photoCandidates.length)});}catch(e:any){return NextResponse.json({error:e?.message||'Falha ao enriquecer dados'},{status:500})}}
