import {NextRequest,NextResponse} from 'next/server';
export const maxDuration=30;
const clean=(s:string)=>s.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&(?:nbsp|amp|quot|#39);/g,' ').replace(/\s+/g,' ').trim();
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const tokens=(s:string)=>norm(s).replace(/\b(dra?|dr)\.?\b/g,'').split(/\s+/).filter(x=>x.length>2&&!['dos','das','uma','para','com'].includes(x));
function registration(t:string){return t.match(/\b(?:CRP|CRM|CRO|CREFITO|CRN|COREN|CRF)(?:[-\s/]?(?:MG|SP|RJ|ES))?\s*(?:N[º°]?\s*)?[\d./-]{3,}\b/i)?.[0]||''}
function phones(t:string){return[...new Set((t.match(/(?:\+?55\s*)?(?:\(?\d{2}\)?\s*)?(?:9\s*)?\d{4}[-.\s]?\d{4}/g)||[]).filter(x=>{const n=x.replace(/\D/g,'');return n.length>=10&&n.length<=13}))]}
function hrefPhones(h:string){const out:string[]=[];for(const m of h.matchAll(/href=["'](?:tel:|https?:\/\/(?:wa\.me|api\.whatsapp\.com\/send\?phone=))([^"'&?]+)/gi)){const n=(m[1]||'').replace(/\D/g,'');if(n.length>=10&&n.length<=13)out.push(n)}return[...new Set(out)]}
function instagram(t:string){const m=t.match(/instagram\.com\/([a-zA-Z0-9._]{3,30})/i)||t.match(/(?:^|\s)@([a-zA-Z0-9._]{3,30})/i);return m?.[1]||''}
function instagramHref(h:string){for(const m of h.matchAll(/href=["'](https?:\/\/(?:www\.)?instagram\.com\/([a-zA-Z0-9._]{3,30})\/?)/gi)){const x=(m[2]||'').toLowerCase();if(!['p','reel','reels','stories','explore','accounts'].includes(x))return m[2]}return''}
function address(t:string,city:string){const c=city.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const a=t.match(new RegExp(`((?:Rua|R\\.|Avenida|Av\\.|Praça|Pça\\.|Praca|Alameda|Travessa|Rodovia)\\s+.{3,150}?\\s*,?\\s*\\d{1,6}.{0,100}?(?:${c}))`,'i'))?.[1]||t.match(/((?:Rua|R\.|Avenida|Av\.|Praça|Pça\.|Praca|Alameda|Travessa|Rodovia)\s+[A-Za-zÀ-ÿ0-9 .,'º°\/-]{3,120}\s*,?\s*\d{1,6}(?:\s*[-–,][A-Za-zÀ-ÿ0-9 .,'º°\/-]{0,80})?)/i)?.[1]||'';return a.replace(/\s+/g,' ').trim()}
function clinic(t:string,name:string){const n=norm(name);return t.split(/[|•]/).map(x=>x.trim()).find(x=>x.length<110&&/(cl[ií]nica|consult[oó]rio|instituto|hospital|centro|odontol[oó]g)/i.test(x)&&!norm(x).includes(n))||''}
function meta(h:string,k:string){const e=k.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return(h.match(new RegExp(`<meta[^>]+(?:property|name)=["']${e}["'][^>]+content=["']([^"']+)`,'i'))?.[1]||'').replace(/&amp;/g,'&')}
type R={url:string;title:string;snippet:string;engine?:string;query?:string;score?:number};
async function bing(q:string):Promise<R[]>{try{const r=await fetch(`https://www.bing.com/search?format=rss&setlang=pt-BR&cc=BR&mkt=pt-BR&q=${encodeURIComponent(q)}`,{headers:{'User-Agent':'Mozilla/5.0 Chrome/124 Safari/537.36','Accept-Language':'pt-BR,pt;q=0.9'},cache:'no-store',signal:AbortSignal.timeout(3500)});if(!r.ok)return[];const x=await r.text();return(x.match(/<item>[\s\S]*?<\/item>/gi)||[]).map(i=>({url:clean(i.match(/<link>([\s\S]*?)<\/link>/i)?.[1]||''),title:clean(i.match(/<title>([\s\S]*?)<\/title>/i)?.[1]||''),snippet:clean(i.match(/<description>([\s\S]*?)<\/description>/i)?.[1]||''),engine:'bing',query:q})).filter(x=>/^https?:/.test(x.url)).slice(0,10)}catch{return[]}}
async function duck(q:string):Promise<R[]>{try{const r=await fetch(`https://html.duckduckgo.com/html/?kl=br-pt&q=${encodeURIComponent(q)}`,{headers:{'User-Agent':'Mozilla/5.0 Chrome/124 Safari/537.36','Accept-Language':'pt-BR,pt;q=0.9'},cache:'no-store',signal:AbortSignal.timeout(3500)});if(!r.ok)return[];const h=await r.text(),out:R[]=[];for(const b of h.split(/class="result\s/).slice(1)){let u=b.match(/class="result__a"[^>]*href="([^"]+)/i)?.[1]||'';try{const x=new URL(u.startsWith('//')?'https:'+u:u),d=x.searchParams.get('uddg');if(d)u=decodeURIComponent(d)}catch{}if(/^https?:/.test(u))out.push({url:u,title:clean(b.match(/class="result__a"[^>]*>([\s\S]*?)<\/a>/i)?.[1]||''),snippet:clean(b.match(/class="result__snippet"[^>]*>([\s\S]*?)<\/(?:a|div)>/i)?.[1]||''),engine:'duckduckgo',query:q})}return out.slice(0,10)}catch{return[]}}
async function search(q:string){const[a,b]=await Promise.all([bing(q),duck(q)]);return[...new Map([...a,...b].map(x=>[x.url,x])).values()]}
function host(u:string){try{return new URL(u).hostname.toLowerCase()}catch{return''}}
function brazilScore(r:R,name:string,city:string,state:string,specialty:string){const t=norm(`${r.title} ${r.snippet} ${r.url}`),nt=tokens(name),st=tokens(specialty),h=host(r.url);let s=0;const hits=nt.filter(k=>t.includes(k)).length;if(hits===nt.length&&nt.length)s+=10;else if(hits>=Math.min(2,nt.length))s+=5;if(city&&t.includes(norm(city)))s+=8;if(state&&new RegExp(`(?:^|[^a-z])${norm(state)}(?:[^a-z]|$)`).test(t))s+=2;if(st.some(k=>t.includes(k)))s+=3;if(/\.br$/.test(h)||h.includes('.br'))s+=7;if(/doctoralia\.com\.br|guiasaude|instagram\.com|facebook\.com|linkedin\.com|google\.com\/maps|clinica|hospital|saude|med\.br|crm|cro|crp/i.test(h))s+=3;if(/healthgrades|webmd|npiprofile|healthcare6|zocdoc|vitals\.com|doximity|usnews/i.test(h))s-=15;if(/\b(?:united states|usa|florida|california|texas|new york|md\b|npi\b)\b/i.test(t)&&!t.includes(norm(city)))s-=10;return s}
function safeUrl(u:string){try{const x=new URL(u);return ['http:','https:'].includes(x.protocol)&&!/(google\.|bing\.com|duckduckgo\.com|yahoo\.com)/i.test(x.hostname)}catch{return false}}
async function page(url:string){try{if(!safeUrl(url))return null;const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124 Safari/537.36','Accept-Language':'pt-BR,pt;q=0.9'},redirect:'follow',cache:'no-store',signal:AbortSignal.timeout(4500)});if(!r.ok)return null;const type=r.headers.get('content-type')||'';if(!type.includes('text/html'))return null;const html=await r.text();return{html,text:clean(html),url:r.url}}catch{return null}}
function identity(text:string,name:string,city:string,specialty:string){const n=norm(text),nt=tokens(name),st=tokens(specialty),hits=nt.filter(k=>n.includes(k)).length,cityHit=Boolean(city&&n.includes(norm(city))),specHit=st.some(k=>n.includes(k)),reg=Boolean(registration(text));const strongName=hits===nt.length&&nt.length>0,partial=hits>=Math.min(2,nt.length);const ok=strongName&&(cityHit||specHit||reg)||partial&&cityHit&&(specHit||reg);return{ok,hits,cityHit,specHit,reg,score:(strongName?8:partial?4:0)+(cityHit?4:0)+(specHit?2:0)+(reg?2:0)}}
async function discover(queries:string[],name:string,city:string,state:string,specialty:string){const rows=(await Promise.all(queries.map(search))).flat();return[...new Map(rows.map(x=>[x.url,x])).values()].map(r=>({...r,score:brazilScore(r,name,city,state,specialty)})).sort((a,b)=>(b.score||0)-(a.score||0))}
async function openAndVerify(ranked:R[],name:string,city:string,specialty:string,limit=10){const opened=(await Promise.all(ranked.slice(0,limit).map(async result=>({result,page:await page(result.url)})))).filter(x=>x.page) as any[];const verified=opened.map(x=>({...x,id:identity(x.page.text,name,city,specialty)})).filter(x=>x.id.ok).sort((a,b)=>b.id.score-a.id.score);return{opened,verified}}
export async function POST(req:NextRequest){try{const b=await req.json(),name=String(b.name||'').trim(),city=String(b.city||'').trim(),state=String(b.state||'MG').trim(),specialty=String(b.specialty||'').trim();if(!name)return NextResponse.json({error:'Nome obrigatório'},{status:400});
const nt=tokens(name),base=`"${name}" "${city}" "${state}"`;const primaryQs=[`${base} Brasil`,`${base} ${specialty}`,`${base} médico telefone`,`${base} consultório clínica`,`${base} CRM CRO CRP`,`${base} site:.br`];
let ranked=await discover(primaryQs,name,city,state,specialty);let first=await openAndVerify(ranked,name,city,specialty,10);let opened=first.opened,verified=first.verified;let retryQs:string[]=[];
if(!verified.length){retryQs=[`"${name}" ${city} MG`,`${nt.join(' ')} ${city} ${specialty} Brasil`,`${name} ${city} doctoralia`,`${name} ${city} instagram`,`${name} ${city} clínica`,`${name} ${city} telefone`];const retry=await discover(retryQs,name,city,state,specialty);const seen=new Set(ranked.map(x=>x.url));ranked=[...ranked,...retry.filter(x=>!seen.has(x.url))].sort((a,b)=>(b.score||0)-(a.score||0));const second=await openAndVerify(ranked,name,city,specialty,14);opened=second.opened;verified=second.verified}
let reg='',addr='',cl='',inst='';let ps:string[]=[];const photos:any[]=[],locations:any[]=[];for(const d of verified){const text=d.page.text,html=d.page.html;reg=reg||registration(text);addr=addr||address(text,city);cl=cl||clinic(text,name);inst=inst||instagramHref(html)||instagram(`${d.page.url} ${text}`);ps=[...new Set([...ps,...hrefPhones(html),...phones(text)])];const image=meta(html,'og:image');if(image&&/^https?:/.test(image)){const x={url:image,sourcePage:d.page.url,title:meta(html,'og:title')||name,identityScore:d.id.score,status:'awaiting_identity_confirmation'};if(!photos.some(y=>y.url===image))photos.push(x)}}
const snippetRelevant=ranked.filter(r=>(r.score||0)>=15);for(const r of snippetRelevant){const t=`${r.title} ${r.snippet}`;reg=reg||registration(t);if(!addr)addr=address(t,city);if(!inst)inst=instagram(t)}
const sources=verified.map(d=>({url:d.page.url,title:d.result.title||name,engine:d.result.engine,query:d.result.query,identityScore:d.id.score,snippet:d.result.snippet}));const engines=[...new Set(ranked.map(x=>x.engine).filter(Boolean))];const found=Boolean(reg||addr||cl||ps.length||inst||photos.length);return NextResponse.json({registration:reg,address:addr,clinic:cl,phone:ps[0]||'',whatsapp:ps.find(x=>x.replace(/\D/g,'').length>=11)||ps[0]||'',instagram:inst?`@${inst}`:'',sources,photoCandidates:photos.slice(0,8),locationPhotoCandidates:locations,facts:{phones:ps.slice(0,6),verifiedPages:verified.length,openedPages:opened.length,sourceCount:sources.length},diagnostics:{contact:Boolean(ps.length),location:Boolean(addr||cl),instagram:Boolean(inst),photo:Boolean(photos.length),sources:sources.length,verifiedPages:verified.length,openedPages:opened.length,queries:primaryQs.length+retryQs.length,freeMultiPass:true,localBrazilPriority:true,retryUsed:Boolean(retryQs.length),rawResults:ranked.length,relevantResults:verified.length,engines,candidateUrls:ranked.slice(0,14).map(x=>x.url)},found})}catch(e:any){return NextResponse.json({error:e?.message||'Falha ao enriquecer dados'},{status:500})}}
