import {NextRequest,NextResponse} from 'next/server';
export const maxDuration=30;
const FETCHABLE=['doctoralia.com.br','psitto.com.br','guiasaude.app.br','minasgerais.net.br','codental.site','dentmap.com.br','instagram.com','facebook.com','linkedin.com','cro-mg.org.br','crmmg.org.br','crp04.org.br','crefito4.gov.br','escavador.com','cnpj.biz'];
const TRUSTED=/doctoralia\.com\.br|psitto\.com\.br|guiasaude\.app\.br|minasgerais\.net\.br|codental\.site|dentmap\.com\.br|cro-mg\.org\.br|crmmg\.org\.br|crp04\.org\.br|crefito4\.gov\.br/i;
const clean=(s:string)=>s.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&(?:nbsp|amp);/g,' ').replace(/\s+/g,' ').trim();
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const tokens=(s:string)=>norm(s).replace(/\b(dra?|dr)\.?\b/g,'').split(/\s+/).filter(x=>x.length>2);
function registration(t:string){return t.match(/\b(?:CRP|CRM|CRO|CREFITO|CRN|COREN|CRF)(?:[-\s]?(?:MG|SP|RJ|ES))?\s*(?:N[º°]?\s*)?[\d./-]{3,}\b/i)?.[0]||''}
function phones(t:string){return[...new Set((t.match(/(?:\+?55\s*)?(?:\(?\d{2}\)?\s*)?(?:9\s*)?\d{4}[-.\s]?\d{4}/g)||[]).filter(x=>{const n=x.replace(/\D/g,'');return n.length>=10&&n.length<=13}))]}
function hrefPhones(h:string){const out:string[]=[];for(const m of h.matchAll(/href=["'](?:tel:|https?:\/\/(?:wa\.me|api\.whatsapp\.com\/send\?phone=))([^"'&?]+)/gi)){const n=(m[1]||'').replace(/\D/g,'');if(n.length>=10&&n.length<=13)out.push(n)}return[...new Set(out)]}
function instagram(t:string){const m=t.match(/instagram\.com\/([a-zA-Z0-9._]{3,30})/i)||t.match(/(?:^|\s)@([a-zA-Z0-9._]{3,30})/i);return m?.[1]||''}
function instagramHref(h:string){for(const m of h.matchAll(/href=["'](https?:\/\/(?:www\.)?instagram\.com\/([a-zA-Z0-9._]{3,30})\/?)/gi)){const x=(m[2]||'').toLowerCase();if(!['p','reel','reels','stories','explore','accounts'].includes(x))return m[2]}return''}
function address(t:string,city:string){const c=city.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const withCity=t.match(new RegExp(`((?:Rua|R\\.|Avenida|Av\\.|Praça|Pça\\.|Alameda|Travessa|Rodovia)\\s+.{3,180}?(?:${c})(?:\\s*[-–,]?\\s*[A-Z]{2})?)`,'i'))?.[1]?.trim();if(withCity)return withCity;return t.match(/((?:Rua|R\.|Avenida|Av\.|Praça|Pça\.|Alameda|Travessa|Rodovia)\s+[A-Za-zÀ-ÿ0-9 .,'º°-]{3,100}\s*,?\s*\d{1,6}(?:\s*[-–,][^|•]{0,80})?)/i)?.[1]?.trim()||''}
function clinic(t:string,name:string){const n=norm(name);return t.split(/[|•]/).map(x=>x.trim()).find(x=>x.length<120&&/(cl[ií]nica|consult[oó]rio|instituto|hospital|centro|odontol[oó]g)/i.test(x)&&!norm(x).includes(n))||''}
function meta(h:string,k:string){const e=k.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return(h.match(new RegExp(`<meta[^>]+(?:property|name)=["']${e}["'][^>]+content=["']([^"']+)`,'i'))?.[1]||'').replace(/&amp;/g,'&')}
type R={url:string;title:string;snippet:string;engine?:string;query?:string;score?:number};
async function duck(q:string):Promise<R[]>{try{const r=await fetch(`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`,{headers:{'User-Agent':'Mozilla/5.0'},cache:'no-store',signal:AbortSignal.timeout(3500)});if(!r.ok)return[];const h=await r.text();return h.split(/class="result\s/).slice(1).map(b=>{let u=b.match(/class="result__a"[^>]*href="([^"]+)/i)?.[1]||'';try{const x=new URL(u.startsWith('//')?'https:'+u:u),d=x.searchParams.get('uddg');if(d)u=decodeURIComponent(d)}catch{}return{url:u,title:clean(b.match(/class="result__a"[^>]*>([\s\S]*?)<\/a>/i)?.[1]||''),snippet:clean(b.match(/class="result__snippet"[^>]*>([\s\S]*?)<\/(?:a|div)>/i)?.[1]||''),engine:'duckduckgo',query:q}}).filter(x=>/^https?:/.test(x.url)).slice(0,10)}catch{return[]}}
async function bing(q:string):Promise<R[]>{try{const r=await fetch(`https://www.bing.com/search?format=rss&q=${encodeURIComponent(q)}`,{headers:{'User-Agent':'Mozilla/5.0'},cache:'no-store',signal:AbortSignal.timeout(3500)});if(!r.ok)return[];const x=await r.text();return(x.match(/<item>[\s\S]*?<\/item>/gi)||[]).map(i=>({url:clean(i.match(/<link>([\s\S]*?)<\/link>/i)?.[1]||''),title:clean(i.match(/<title>([\s\S]*?)<\/title>/i)?.[1]||''),snippet:clean(i.match(/<description>([\s\S]*?)<\/description>/i)?.[1]||''),engine:'bing',query:q})).filter(x=>/^https?:/.test(x.url)).slice(0,10)}catch{return[]}}
async function search(q:string){const[a,b]=await Promise.all([duck(q),bing(q)]);return[...new Map([...a,...b].map(x=>[x.url,x])).values()]}
function score(r:R,name:string,specialty:string,city:string,state:string){const t=norm(`${r.title} ${r.snippet} ${r.url}`),nt=tokens(name),st=tokens(specialty);let s=0;const hits=nt.filter(k=>t.includes(k)).length;if(nt.length&&hits===nt.length)s+=8;else if(hits>=Math.min(2,nt.length))s+=4;if(city&&t.includes(norm(city)))s+=4;if(state&&t.includes(norm(state)))s++;if(st.some(k=>t.includes(k)))s+=2;if(TRUSTED.test(r.url))s+=2;if(/instagram\.com|facebook\.com|linkedin\.com/i.test(r.url))s++;return s}
async function page(url:string){try{const host=new URL(url).hostname.toLowerCase();if(!FETCHABLE.some(d=>host===d||host.endsWith('.'+d)))return null;const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0'},cache:'no-store',signal:AbortSignal.timeout(4000)});if(!r.ok)return null;const html=await r.text();return{html,text:clean(html)}}catch{return null}}
function relevantResults(all:R[],name:string,specialty:string,city:string,state:string){const nt=tokens(name),ct=norm(city),st=tokens(specialty);return all.map(r=>({...r,score:score(r,name,specialty,city,state)})).sort((a,b)=>(b.score||0)-(a.score||0)).filter(r=>{const t=norm(`${r.title} ${r.snippet} ${r.url}`),hits=nt.filter(k=>t.includes(k)).length,cityHit=Boolean(ct&&t.includes(ct)),specHit=st.some(k=>t.includes(k));return hits>=Math.min(2,nt.length)&&((cityHit&&(r.score||0)>=6)||(specHit&&(r.score||0)>=8)||(r.score||0)>=10)});}
export async function POST(req:NextRequest){try{const b=await req.json(),name=String(b.name||'').trim(),city=String(b.city||'').trim(),state=String(b.state||'MG').trim(),specialty=String(b.specialty||'').trim();if(!name)return NextResponse.json({error:'Nome obrigatório'},{status:400});
const nt=tokens(name),variants=[nt.join(' '),nt.slice(0,-1).join(' '),nt.slice(0,2).join(' '),nt.length>2?`${nt[0]} ${nt[nt.length-1]}`:''].filter((x,i,a)=>x&&a.indexOf(x)===i);
const primary=[`"${name}" "${city}" ${state}`,`"${name}" "${specialty}" "${city}"`,`"${name}" ${city} telefone`,`"${name}" ${city} whatsapp`,`"${name}" ${city} contato`,`"${name}" ${city} endereço`,`"${name}" ${city} consultório clínica`,`"${name}" ${city} instagram`,`site:instagram.com "${name}" ${city}`,`site:facebook.com "${name}" ${city}`,`site:doctoralia.com.br "${name}"`,`site:guiasaude.app.br "${name}"`,`site:minasgerais.net.br "${name}"`,`"${name}" CRO CRM CRP CREFITO CRN ${state}`];
let all=[...(await Promise.all(primary.map(search))).flat().reduce((m,r)=>m.set(r.url,r),new Map<string,R>()).values()];let relevant=relevantResults(all,name,specialty,city,state);
if(relevant.length<4){const fallback=variants.flatMap(v=>[`${v} ${city} ${state}`,`"${v}" ${city}`,`${v} ${specialty} ${city}`,`${v} telefone ${city}`,`${v} consultório ${city}`,`site:minasgerais.net.br "${v}"`, `site:doctoralia.com.br "${v}"`, `site:instagram.com "${v}" ${city}`]);fallback.push(`${specialty} ${city} ${state} ${nt.slice(0,2).join(' ')}`,`dentistas ${city} ${state} ${nt.slice(0,2).join(' ')}`);const fb=(await Promise.all([...new Set(fallback)].map(search))).flat();all=[...new Map([...all,...fb].map(x=>[x.url,x])).values()];relevant=relevantResults(all,name,specialty,city,state)}
relevant=relevant.slice(0,30);const docs=(await Promise.all(relevant.slice(0,18).map(async result=>({result,page:await page(result.url)})))).filter(x=>x.page) as any[];let reg='',addr='',cl='',inst='';let ps:string[]=[];const photos:any[]=[],locations:any[]=[];
for(const r of relevant){const text=`${r.title} ${r.snippet} ${r.url}`;reg=reg||registration(text);addr=addr||address(text,city);cl=cl||clinic(text,name);inst=inst||instagram(text);ps=[...new Set([...ps,...phones(text)])]}
for(const d of docs){const text=d.page.text,html=d.page.html;reg=reg||registration(text);addr=addr||address(text,city);cl=cl||clinic(text,name);inst=inst||instagramHref(html)||instagram(`${d.result.url} ${text}`);ps=[...new Set([...ps,...hrefPhones(html),...phones(text)])];const image=meta(html,'og:image');if(image&&/^https?:/.test(image)){const x={url:image,sourcePage:d.result.url,title:meta(html,'og:title')||name,identityScore:d.result.score,status:'awaiting_identity_confirmation'};if(!photos.some(y=>y.url===image))photos.push(x);if(/clinica|consultorio|instituto|hospital|endereco|fachada|unidade|odontolog/i.test(text)&&!locations.some(y=>y.url===image))locations.push({...x,status:'awaiting_location_confirmation'})}}
const sources=relevant.map(x=>({url:x.url,title:x.title,engine:x.engine,query:x.query,identityScore:x.score}));const found=Boolean(reg||addr||cl||ps.length||inst||photos.length);return NextResponse.json({registration:reg,address:addr,clinic:cl,phone:ps[0]||'',whatsapp:ps.find(x=>x.replace(/\D/g,'').length>=11)||ps[0]||'',instagram:inst?`@${inst}`:'',sources,photoCandidates:photos.slice(0,8),locationPhotoCandidates:locations.slice(0,8),facts:{phones:ps.slice(0,6),verifiedPages:docs.length,sourceCount:sources.length},diagnostics:{contact:Boolean(ps.length),location:Boolean(addr||cl),instagram:Boolean(inst),photo:Boolean(photos.length),locationPhoto:Boolean(locations.length),sources:sources.length,verifiedPages:docs.length,queries:primary.length+variants.length*8,freeMultiPass:true,nameVariants:variants},found})}catch(e:any){return NextResponse.json({error:e?.message||'Falha ao enriquecer dados'},{status:500})}}
