import type { CSSProperties } from 'react';
import type { Professional } from '../../lib/professionals';
type ThemeStyle=CSSProperties & Record<`--${string}`,string>;
export default function Care01({p}:{p:Professional}){const mapQuery=encodeURIComponent([p.clinic,p.address].filter(Boolean).join(' '));const faqs=p.faqs||[];const initials=p.shortName.split(' ').filter(Boolean).slice(-2).map(x=>x[0]).join('');const style:ThemeStyle={'--care':p.theme?.primary||'#6b594f','--care-accent':p.theme?.secondary||'#b08f7e','--care-bg':p.theme?.background||'#f5f0e9'};return <main className="care01" style={style}>
{p.status==='demo'&&<div className="cDemo"><span>37LAB / CARE 01</span><b>DEMONSTRAÇÃO PRIVADA</b><span>NÃO INDEXADA</span></div>}
<header className="cHeader"><a className="cBrand" href="#inicio"><i>◌</i><span><strong>{p.shortName}</strong><small>{p.specialty}</small></span></a><nav><a href="#sobre">Sobre</a><a href="#cuidado">Atuação</a><a href="#local">Atendimento</a><a href="#faq">Dúvidas</a></nav>{p.whatsapp&&<a className="cHeaderCta" href={`https://wa.me/${p.whatsapp}`} target="_blank" rel="noreferrer">Agendar conversa</a>}</header>
<section id="inicio" className="cHero"><div className="cHeroText"><span className="cKicker">{p.eyebrow||'ESCUTA • CUIDADO • PRESENÇA'}</span><h1>{p.heroTitle||'Um espaço para'}<br/><em>{p.heroEmphasis||'cuidar de você.'}</em></h1><p>{p.bio}</p><div className="cActions">{p.whatsapp&&<a href={`https://wa.me/${p.whatsapp}`} target="_blank" rel="noreferrer">Agendar atendimento <b>↗</b></a>}<a href="#sobre">Conhecer meu trabalho</a></div></div><div className="cHeroPhoto">{p.professionalImage?<img src={p.professionalImage} alt={`Foto profissional de ${p.name}`}/>:<div className="cPortrait"><span>{initials}</span><small>FOTO PROFISSIONAL</small></div>}<div className="cNote">{p.careLabel||'acolhimento e cuidado individualizado'}</div></div></section>
<section className="cManifest"><span>01</span><p>{p.quote||'Cada pessoa tem seu próprio tempo, sua história e sua forma de atravessar os processos da vida.'}</p></section>
<section id="sobre" className="cAbout"><div><span className="cIndex">02 / SOBRE</span><h2>{p.aboutTitle||'Cuidado que começa pela escuta.'}</h2></div><div><p>{p.aboutText||p.bio}</p><div className="cCredentials"><span>{p.profession}</span>{p.registration&&<span>{p.registration}</span>}<span>{p.city} / {p.state}</span></div></div></section>
<section id="cuidado" className="cServices"><div className="cServicesTitle"><span className="cIndex">03 / COMO POSSO AJUDAR</span><h2>Um cuidado pensado<br/>para cada momento.</h2></div><div className="cCards">{p.services.map((s,i)=><article key={s.title}><span>{String(i+1).padStart(2,'0')}</span><h3>{s.title}</h3><p>{s.description}</p></article>)}</div></section>
<section className="cPause"><small>PRESENÇA • ESCUTA • PROCESSO</small><h2>Cuidar também é criar<br/><em>espaço para compreender.</em></h2></section>
{(p.clinic||p.address)&&<section id="local" className="cLocation"><div className="cLocationPhoto">{p.clinicImage?<img src={p.clinicImage} alt={p.clinic||'Espaço de atendimento'}/>:<div><span>◌</span><small>ESPAÇO DE ATENDIMENTO</small></div>}</div><div className="cLocationText"><span className="cIndex">04 / ATENDIMENTO</span><h2>{p.clinic||'Espaço de atendimento'}</h2>{p.address&&<p>{p.address}</p>}{p.phone&&<a href={`tel:${p.phone.replace(/\D/g,'')}`}>{p.phone}</a>}<a className="cMap" href={`https://www.google.com/maps/search/?api=1&query=${mapQuery}`} target="_blank" rel="noreferrer">Ver localização ↗</a></div></section>}
{faqs.length>0&&<section id="faq" className="cFaq"><div><span className="cIndex">05 / DÚVIDAS</span><h2>Antes de<br/>começarmos.</h2></div><div>{faqs.map(f=><details key={f.question}><summary>{f.question}<b>＋</b></summary><p>{f.answer}</p></details>)}</div></section>}
<section className="cContact"><span>PRÓXIMO PASSO</span><h2>Podemos começar<br/>com uma conversa.</h2><p>Entre em contato para consultar horários e informações sobre o atendimento.</p>{p.whatsapp&&<a href={`https://wa.me/${p.whatsapp}`} target="_blank" rel="noreferrer">Falar pelo WhatsApp ↗</a>}</section>
<footer className="cFooter"><div className="cBrand"><i>◌</i><span><strong>{p.shortName}</strong><small>{p.specialty}</small></span></div><div>{p.registration&&<span>{p.registration}</span>}<span>{p.city} / {p.state}</span></div><div>{p.instagram&&<a href={p.instagram} target="_blank" rel="noreferrer">Instagram ↗</a>}<span>© {new Date().getFullYear()}</span></div><small>CONCEITO E TECNOLOGIA <b>37LAB</b></small></footer>
</main>}