import {NextRequest,NextResponse} from 'next/server';
export const maxDuration=30;
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const clean=(s:string)=>s.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&(?:nbsp|amp|quot|#39|#x27);/gi,' ').replace(/\s+/g,' ').trim();
const slug=(s:string)=>norm(s).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const toks=(s:string)=>norm(s).replace(/\b(dra?|dr)\.?\b/g,'').split(/\s+/).filter(x=>x.length>2&&!['dos','das','uma','para','com','de','da','do'].includes(x));
const digits=(s:string)=>s.replace(/\D/g,'');
function phone(t:string){return (t.match(/(?:\+?55\s*)?(?:\(?\d{2}\)?\s*)?(?:9\s*)?\d{4}[-.\s]?\d{4}/g)||[]).find(x=>{const n=digits(x);return n.length>=10&&n.length<=13})||''}
function whatsapp(t:string){for(const r of [/(?:WhatsApp|Whatsapp|whats|wa\.me)[^\d]{0,40}((?:\+?55\s*)?(?:\(?\d{2}\)?\s*)?(?:9\s*)?\d{4}[-.\s]?\d{4})/i,/((?:\+?55\s*)?(?:\(?\d{2}\)?\s*)?(?:9\s*)?\d{4}[-.\s]?\d{4})[^A-Za-zÀ-ÿ]{0,25}(?:WhatsApp|Whatsapp|whats)/i]){const m=t.match(r);if(m?.[1])return digits(m[1])}return''}
function registration(t:string){return t.match(/\b(?:CRP|CRM|CRO|CREFITO|CRN|COREN|CRF)(?:[-\s/]?(?:MG|SP|RJ|ES))?\s*(?:N[º°]?\s*)?[\d./-]{3,}\b/i)?.[0]||''}
function address(t:string){const m=t.match(/((?:Rua|R\.|Avenida|Av\.|Praça|Pça\.|Praca|Pc\.?|Alameda|Travessa|Rodovia)\s+[A-Za-zÀ-ÿ0-9 .,'º°\/-]{3,120}\s*,?\s*\d{1,6}(?:\s*[-–,][A-Za-zÀ-ÿ0-9 .,'º°\/-]{0,70})?)/i)?.[1]||'';return m.replace(/\s*(?:\(?\d{2}\)?\s*)?(?:9\s*)?\d{4}[-.\s]?\d{4}.*$/i,'').replace(/\s+(?:ver|mostrar|exibir)\s+telefone.*$/i,'').replace(/[\s,;.-]+$/,'').trim()}
function clinic(t:string,name:string){for(const m of t.matchAll(/(?:Consult[oó]rio|Cl[ií]nica|Centro|Instituto|Hospital|Santa Casa|APAE)\s+[A-Za-zÀ-ÿ0-9 &'().,-]{2,80}/gi)){let x=m[0].replace(/\s+(?:Rua|R\.|Avenida|Av\.|Praça|Pça\.|Endereço|Telefone|WhatsApp).*$/i,'').trim();if(x.length<90&&!toks(name).every(k=>norm(x).includes(k)))return x}return''}
function instagram(t:string){const m=t.match(/instagram\.com\/([a-zA-Z0-9._]{3,30})/i)||t.match(/(?:^|\s)@([a-zA-Z0-9._]{3,30})/i);return m?.[1]?`@${m[1]}`:''}
function role(s:string){s=norm(s);if(/psic/.test(s))return'psicologo';if(/pediatr/.test(s))return'pediatra';if(/odonto|dent|ortodont/.test(s))return'dentista';if(/fisi/.test(s))return'fisioterapeuta';if(/nutri/.test(s))return'nutricionista';return'medico'}
function safeUrl(u:string){try{const x=new URL(u);const h=x.hostname.toLowerCase();if(!/^https?:$/.test(x.protocol)||h==='localhost'||h.endsWith('.local')||/^127\.|^10\.|^192\.168\.|^169\.254\.|^0\./.test(h))return false;return !/(google\.|bing\.com|duckduckgo\.|yahoo\.com)/i.test(h)}catch{return false}}
async function fetchPage(url:string){try{if(!safeUrl(url))return'';const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124 Safari/537.36','Accept-Language':'pt-BR,pt;q=0.9'},redirect:'follow',cache:'no-store',signal:AbortSignal.timeout(5000)});if(!r.ok)return'';return clean(await r.text())}catch{return''}}
type Candidate={url:string;title:string;snippet:string;engine:string};
async function bing(q:string):Promise<Candidate[]>{try{const r=await fetch(`https://www.bing.com/search?format=rss&setlang=pt-BR&q=${encodeURIComponent(q)}`,{headers:{'User-Agent':'Mozilla/5.0 Chrome/124 Safari/537.36'},cache:'no-store',signal:AbortSignal.timeout(4500)});if(!r.ok)return[];const x=await r.text();return(x.match(/<item>[\s\S]*?<\/item>/gi)||[]).map(i=>({url:clean(i.match(/<link>([\s\S]*?)<\/link>/i)?.[1]||''),title:clean(i.match(/<title>([\s\S]*?)<\/title>/i)?.[1]||''),snippet:clean(i.match(/<description>([\s\S]*?)<\/description>/i)?.[1]||''),engine:'bing'})).filter(x=>safeUrl(x.url)).slice(0,10)}catch{return[]}}
function decodeDuck(v:string){try{const u=new URL(v.startsWith('//')?'https:'+v:v,'https://html.duckduckgo.com'),d=u.searchParams.get('uddg');return d?decodeURIComponent(d):v}catch{return v}}
async function duck(q:string):Promise<Candidate[]>{try{const r=await fetch(`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`,{headers:{'User-Agent':'Mozilla/5.0 Chrome/124 Safari/537.36'},cache:'no-store',signal:AbortSignal.timeout(4500)});if(!r.ok)return[];const h=await r.text(),out:Candidate[]=[];for(const b of h.split(/class="result\s/).slice(1)){const u=decodeDuck(b.match(/class="result__a"[^>]*href="([^"]+)/i)?.[1]||'');if(safeUrl(u))out.push({url:u,title:clean(b.match(/class="result__a"[^>]*>([\s\S]*?)<\/a>/i)?.[1]||''),snippet:clean(b.match(/class="result__snippet"[^>]*>([\s\S]*?)<\/(?:a|div)>/i)?.[1]||''),engine:'duckduckgo'})}return out.slice(0,8)}catch{return[]}}
function identity(text:string,name:string,city:string,specialty:string){const n=norm(text),nt=toks(name),hits=nt.filter(t=>n.includes(t)).length,cityHit=n.includes(norm(city)),spec=toks(specialty).some(t=>n.includes(t));let score=hits*3+(cityHit?5:0)+(spec?2:0);return{ok:hits>=Math.min(2,nt.length)&&cityHit,score,hits,cityHit,spec}}
function extract(text:string,name:string){return{phone:phone(text),whatsapp:whatsapp(text),address:address(text),clinic:clinic(text,name),registration:registration(text),instagram:instagram(text)}}
function merge(base:any,next:any){for(const k of ['phone','whatsapp','address','clinic','registration','instagram'])if(!base[k]&&next[k])base[k]=next[k];return base}
export async function POST(req:NextRequest){try{const b=await req.json(),name=String(b.name||'').trim(),city=String(b.city||'').trim(),specialty=String(b.specialty||'').trim();if(!name||!city)return NextResponse.json({found:false,sources:[]});const q1=`\"${name}\" \"${city}\"`,q2=`\"${name}\" ${specialty} ${city}`;const [b1,b2,d1]=await Promise.all([bing(q1),bing(q2),duck(q1)]);let candidates=[...new Map([...b1,...b2,...d1].map(x=>[x.url,x])).values()];
// Add deterministic public profiles, but never trust them until the page itself confirms identity.
const r=role(specialty),cs=slug(city);for(const u of [`https://www.doctoralia.com.br/${slug(name)}/${r}/${cs}`,`https://www.doctoralia.com.br/${r}/${cs}`])if(!candidates.some(x=>x.url===u))candidates.push({url:u,title:'Perfil público',snippet:'',engine:'structured'});
// Important: raw search results are opened BEFORE snippet relevance filtering. The page, not the snippet, confirms identity.
const opened=await Promise.all(candidates.slice(0,10).map(async c=>({c,text:await fetchPage(c.url)})));const verified=opened.map(x=>({...x,id:x.text?identity(x.text,name,city,specialty):{ok:false,score:0,hits:0,cityHit:false,spec:false}})).filter(x=>x.id.ok).sort((a,b)=>b.id.score-a.id.score);
let data:any={phone:'',whatsapp:'',address:'',clinic:'',registration:'',instagram:''};const sources:any[]=[];for(const v of verified.slice(0,5)){data=merge(data,extract(v.text,name));sources.push({url:v.c.url,title:v.c.title||`Fonte pública de ${name}`,engine:v.c.engine,identityScore:v.id.score})}
const found=Object.values(data).some(Boolean);return NextResponse.json({...data,found,sources,diagnostics:{adapter:'open-then-verify',rawCandidates:candidates.length,openedPages:opened.filter(x=>x.text).length,verifiedPages:verified.length,sourceCount:sources.length,engines:[...new Set(candidates.map(x=>x.engine))],attempts:opened.map(x=>({url:x.c.url,engine:x.c.engine,opened:Boolean(x.text),verified:x.text?identity(x.text,name,city,specialty).ok:false}))}})}catch(e:any){return NextResponse.json({found:false,sources:[],error:e?.message||'Falha no enriquecimento público'})}}