import {NextRequest,NextResponse} from 'next/server';
export const maxDuration=20;
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const clean=(s:string)=>s.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&(?:nbsp|amp|quot|#39);/g,' ').replace(/\s+/g,' ').trim();
const slug=(s:string)=>norm(s).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const toks=(s:string)=>norm(s).replace(/\b(dra?|dr)\.?\b/g,'').split(/\s+/).filter(x=>x.length>2&&!['dos','das','uma','para','com'].includes(x));
const digits=(s:string)=>s.replace(/\D/g,'');
function phone(t:string){return (t.match(/(?:\(?\d{2}\)?\s*)?(?:9\s*)?\d{4}[-.\s]?\d{4}/g)||[]).find(x=>{const n=digits(x);return n.length>=10&&n.length<=11})||''}
function whatsapp(t:string){const patterns=[/(?:WhatsApp|Whatsapp|whats|wa\.me)[^\d]{0,30}((?:\(?\d{2}\)?\s*)?9\s*\d{4}[-.\s]?\d{4})/i,/((?:\(?\d{2}\)?\s*)?9\s*\d{4}[-.\s]?\d{4})[^A-Za-zÀ-ÿ]{0,20}(?:WhatsApp|Whatsapp|whats)/i];for(const r of patterns){const m=t.match(r);if(m?.[1]&&digits(m[1]).length===11)return digits(m[1])}return''}
function registration(t:string){return t.match(/\b(?:CRP|CRM|CRO|CREFITO|CRN|COREN|CRF)(?:[-\s/]?(?:MG|SP|RJ|ES))?\s*(?:N[º°]?\s*)?[\d./-]{3,}\b/i)?.[0]||''}
function tidyAddress(v:string){return v.replace(/\s*(?:\(?\d{2}\)?\s*)?(?:9\s*)?\d{4}[-.\s]?\d{4}.*$/i,'').replace(/\s+(?:ver|mostrar|exibir)\s+telefone.*$/i,'').replace(/\s+(?:Brasil|Brazil)\b.*$/i,'').replace(/[\s,;.-]+$/,'').replace(/\s+/g,' ').trim()}
function address(t:string){const m=t.match(/((?:Rua|R\.|Avenida|Av\.|Praça|Pça\.|Praca|Pc\.?|Alameda|Travessa|Rodovia)\s+[A-Za-zÀ-ÿ0-9 .,'º°\/-]{3,150}\s*,?\s*\d{1,6}(?:\s*[-–,][A-Za-zÀ-ÿ0-9 .,'º°\/-]{0,100})?)/i)?.[1]||'';return tidyAddress(m)}
function tidyClinic(v:string,name:string){let x=v.replace(/\s*(?:Telefone|WhatsApp|Whatsapp|Endereço|Endereco|Ver telefone|Como chegar).*$/i,'').replace(/\s+/g,' ').trim();const generic=/^(?:Cl[ií]nicas?\s+Odontol[oó]gicas?|Dentistas?|Odontologia|Implantes?\s+Dent[aá]rios?|M[eé]dicos?|Psic[oó]logos?|Fisioterapeutas?|Nutricionistas?)(?:\s|$)/i;if(generic.test(x)&&!/(consult[oó]rio|centro|instituto|hospital)/i.test(x))return'';if(x.length>90)return'';const nt=toks(name);if(nt.length&&nt.every(k=>norm(x).includes(k)))return'';return x}
function clinic(t:string,name:string){const candidates=[...(t.matchAll(/(?:Consult[oó]rio|Cl[ií]nica|Centro|Instituto|Hospital|Santa Casa|APAE)\s+[A-Za-zÀ-ÿ0-9 &'().,-]{2,90}/gi))].map(m=>tidyClinic(m[0],name)).filter(Boolean);return candidates[0]||''}
function categories(specialty:string){const s=norm(specialty);if(/odonto|dent|ortodont/.test(s))return['dentistas'];if(/psic/.test(s))return['psicologos'];if(/fisi/.test(s))return['fisioterapeutas'];if(/nutri/.test(s))return['nutricionistas'];if(/fono/.test(s))return['fonoaudiologos'];if(/farmac/.test(s))return['farmacias'];if(/medic|cardio|gineco|pediatr|dermato|oftalmo|ortoped|urolog|neurolog/.test(s))return['medicos'];return['medicos','dentistas','psicologos','fisioterapeutas','nutricionistas'];}
function role(specialty:string){const s=norm(specialty);if(/psic/.test(s))return'psicologo';if(/pediatr/.test(s))return'pediatra';if(/odonto|dent|ortodont/.test(s))return'dentista';if(/fisi/.test(s))return'fisioterapeuta';if(/nutri/.test(s))return'nutricionista';return'medico'}
async function fetchText(url:string){try{const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 Chrome/124 Safari/537.36','Accept-Language':'pt-BR,pt;q=0.9'},cache:'no-store',signal:AbortSignal.timeout(6500)});if(!r.ok)return'';return clean(await r.text())}catch{return''}}
function contextFor(text:string,name:string){const n=norm(text),ts=toks(name);if(!ts.length)return'';const anchors=[ts.join(' '),ts.slice(0,-1).join(' '),ts.slice(0,2).join(' '),ts.length>2?`${ts[0]} ${ts[ts.length-1]}`:''].filter(Boolean);for(const v of anchors){const i=n.indexOf(v);if(i<0)continue;const window=n.slice(Math.max(0,i-180),Math.min(n.length,i+1000)),hits=ts.filter(t=>window.includes(t)).length;if(hits>=Math.min(2,ts.length))return text.slice(Math.max(0,i-220),Math.min(text.length,i+1000))}return''}
function extract(ctx:string,name:string){const p=phone(ctx),w=whatsapp(ctx),a=address(ctx),cl=clinic(ctx,name),reg=registration(ctx);return{phone:p,whatsapp:w,address:a,clinic:cl,registration:reg,found:Boolean(p||w||a||cl||reg)}}
export async function POST(req:NextRequest){try{const b=await req.json(),name=String(b.name||'').trim(),city=String(b.city||'').trim(),specialty=String(b.specialty||'').trim();if(!name||!city)return NextResponse.json({found:false,sources:[]});const citySlug=slug(city),attempts:any[]=[],r=role(specialty);
const urls=[...categories(specialty).map(cat=>({adapter:'minasgerais-directory',url:`https://www.minasgerais.net.br/${cat}-${citySlug}`,label:`Diretório local ${cat} — ${city}`})),{adapter:'doctoralia-listing',url:`https://www.doctoralia.com.br/${r}/${citySlug}`,label:`${r} em ${city} — Doctoralia`},{adapter:'doctoralia-profile',url:`https://www.doctoralia.com.br/${slug(name)}/${r}/${citySlug}`,label:`Perfil público ${name} — ${city}`}];
for(const item of urls){const text=await fetchText(item.url);attempts.push({adapter:item.adapter,loaded:Boolean(text)});if(!text)continue;const ctx=contextFor(text,name);if(!ctx)continue;const data=extract(ctx,name);if(data.found)return NextResponse.json({...data,sources:[{url:item.url,title:item.label,engine:item.adapter,identityScore:12}],diagnostics:{adapter:item.adapter,matched:true,whatsappExplicit:Boolean(data.whatsapp),attempts}})}
return NextResponse.json({found:false,sources:[],diagnostics:{adapter:'free-local-fallbacks',matched:false,categories:categories(specialty),attempts}})}catch(e:any){return NextResponse.json({found:false,sources:[],error:e?.message||'Falha no diretório local'})}}