import {NextRequest,NextResponse} from 'next/server';
export const maxDuration=20;
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const clean=(s:string)=>s.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&(?:nbsp|amp|quot|#39);/g,' ').replace(/\s+/g,' ').trim();
const slug=(s:string)=>norm(s).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const toks=(s:string)=>norm(s).replace(/\b(dra?|dr)\.?\b/g,'').split(/\s+/).filter(x=>x.length>2);
function phone(t:string){return (t.match(/(?:\(?\d{2}\)?\s*)?(?:9\s*)?\d{4}[-.\s]?\d{4}/g)||[]).find(x=>{const n=x.replace(/\D/g,'');return n.length>=10&&n.length<=11})||''}
function address(t:string){return t.match(/((?:Rua|R\.|Avenida|Av\.|Praça|Pça\.|Alameda|Travessa|Rodovia)\s+[A-Za-zÀ-ÿ0-9 .,'º°-]{3,120}\s*,?\s*\d{1,6}(?:\s*[-–,][^|•]{0,100})?)/i)?.[1]?.trim()||''}
function categories(specialty:string){const s=norm(specialty);if(/odonto|dent|ortodont/.test(s))return['dentistas'];if(/psic/.test(s))return['psicologos'];if(/fisi/.test(s))return['fisioterapeutas'];if(/nutri/.test(s))return['nutricionistas'];if(/fono/.test(s))return['fonoaudiologos'];if(/farmac/.test(s))return['farmacias'];if(/medic|cardio|gineco|pediatr|dermato|oftalmo|ortoped|urolog|neurolog/.test(s))return['medicos'];return['medicos','dentistas','psicologos','fisioterapeutas','nutricionistas'];}
async function fetchText(url:string){try{const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 Chrome/124 Safari/537.36','Accept-Language':'pt-BR,pt;q=0.9'},cache:'no-store',signal:AbortSignal.timeout(6500)});if(!r.ok)return'';return clean(await r.text())}catch{return''}}
function contextFor(text:string,name:string){const n=norm(text),ts=toks(name),variants=[ts.join(' '),ts.slice(0,-1).join(' '),ts.slice(0,2).join(' '),ts.length>2?`${ts[0]} ${ts[ts.length-1]}`:''].filter(Boolean);let best=-1;for(const v of variants){const i=n.indexOf(v);if(i>=0){best=i;break}}if(best<0)return'';return text.slice(Math.max(0,best-180),Math.min(text.length,best+700));}
export async function POST(req:NextRequest){try{const b=await req.json(),name=String(b.name||'').trim(),city=String(b.city||'').trim(),specialty=String(b.specialty||'').trim();if(!name||!city)return NextResponse.json({found:false,sources:[]});const citySlug=slug(city);for(const cat of categories(specialty)){const url=`https://www.minasgerais.net.br/${cat}-${citySlug}`,text=await fetchText(url);if(!text)continue;const ctx=contextFor(text,name);if(!ctx)continue;const p=phone(ctx),a=address(ctx),clinic=(ctx.match(/(?:Consult[oó]rio|Cl[ií]nica|Centro|Instituto)[^|•]{0,100}/i)?.[0]||'').trim();return NextResponse.json({found:Boolean(p||a||clinic),phone:p,whatsapp:'',address:a,clinic,sources:[{url,title:`Diretório local ${cat} — ${city}`,engine:'direct-local-directory',identityScore:12}],diagnostics:{adapter:'minasgerais-directory',category:cat,matched:true}})}return NextResponse.json({found:false,sources:[],diagnostics:{adapter:'minasgerais-directory',matched:false,categories:categories(specialty)}})}catch(e:any){return NextResponse.json({found:false,sources:[],error:e?.message||'Falha no diretório local'})}}
